ergoPack: include/ODECont.hpp File Reference
ODECont.hpp File Reference
Continuation of Ordinary Differential Equations.
#include <vector>
#include <gsl/gsl_math.h>
#include <gsl/gsl_vector.h>
#include <gsl/gsl_matrix.h>
#include <gsl/gsl_blas.h>
Classes
class solutionCorrection
Abstract class for Newton corrections.
class fixedPointTrack
Abstract class Newton correction of fixed points.
class fixedPointCorr
Newton correction of fixed points.
class solutionCont
Abstract base class for continuation.
class fixedPointCont
Continuation of fixed points.
class periodicOrbitTrack
Abstract class Newton correction of periodic orbits.
class periodicOrbitCorr
Newton correction of periodic orbits.
class periodicOrbitCont
Continuation of periodic orbits.
Functions
void getCovarianceMatrix (const std::vector< gsl_matrix *> &Qs, const std::vector< gsl_matrix *> *Mts, gsl_matrix *CT, const double dt=1.)
Calculate covariance matrix from M(t, s) and Q(s).
double getPhaseDiffusion (const gsl_matrix *CT, const gsl_vector *vLeft, const gsl_vector *vRight, const double T=1.)
Calculate phase diffusion coefficient from covariance matrix.
double getPhaseDiffusion (const std::vector< gsl_matrix *> *Qs, const std::vector< gsl_matrix *> *Mts, const gsl_vector *vLeft, const gsl_vector *vRight, const double dt=1.)
void getFloquet (periodicOrbitCont *track, gsl_vector *state, gsl_vector_complex *FloquetExp, gsl_matrix_complex *eigVecLeft, gsl_matrix_complex *eigVecRight, const bool sort=false, const bool norm=false)
Get Floquet elements from continuation.
void writeFloquet (periodicOrbitCont *track, const gsl_vector *state, const gsl_vector_complex *FloquetExp, const gsl_matrix_complex *eigVecLeft, const gsl_matrix_complex *eigVecRight, FILE *streamState, FILE *streamExp, FILE *streamVecLeft, FILE *streamVecRight, const char *fileFormat="txt", const bool verbose=false)
Write Floquet eigenvalues and left and right eigenvectors.
void sortSpectrum (gsl_vector_complex *eigValLeft, gsl_matrix_complex *eigVecLeft, gsl_vector_complex *eigValRight, gsl_matrix_complex *eigVecRight)
Sort eigenelements by largest magnitude of eigenvalue.
void normalizeFloquet (periodicOrbitCont *track, const gsl_vector_complex *FloquetExp, gsl_matrix_complex *eigVecLeft, gsl_matrix_complex *eigVecRight)
Normalize the Floquet vectors given a continuation problem.
void normalizeFloquet (const gsl_vector *stateCont, vectorField *field, const gsl_vector_complex *FloquetExp, gsl_matrix_complex *eigVecLeft, gsl_matrix_complex *eigVecRight)
Normalize the Floquet vectors given a state and a vector field.
Detailed Description
Continuation of Ordinary Differential Equations.
Definition in file ODECont.hpp.
Function Documentation
getFloquet()
void getFloquet (periodicOrbitCont * track, gsl_vector * state, gsl_vector_complex * FloquetExp, gsl_matrix_complex * eigVecLeft, gsl_matrix_complex * eigVecRight, const bool sort, const bool norm)
Get Floquet eigenvalues and left and right eigenvectors from the current state of the periodic orbit continuation.
Parameters
[in] track Periodic ontinuation problem.
[out] state State vector on orbit.
[out] FloquetExp Floquet exponents.
[out] eigVecLeft Left Floquet vectors.
[out] eigVecRight Right Floquet vectors.
[in] sort Whether to sort the spectrum or not.
[in] norm Whether to normalize the Floquet vectors or not.
Definition at line 1612 of file ODECont.cpp.
References solutionCorrection::dim, periodicOrbitCont::getCurrentState(), solutionCorrection::getDim(), periodicOrbitTrack::getStabilityMatrix(), gsl_vector_complex_log(), gsl_vector_complex_scale_real(), normalizeFloquet(), and sortSpectrum().
Referenced by periodicOrbitCont::periodicOrbitCont().
getPhaseDiffusion() [1/2]
double getPhaseDiffusion (const gsl_matrix * CT, const gsl_vector * vLeft, const gsl_vector * vRight, const double T)
Calculate phase diffusion coefficient from covariance matrix .
Parameters
[in] CT Covariance matrix.
[in] vLeft Left vector on which to project.
[in] vRight Right vector on which to project.
[in] T Period of integration.
Returns
Phase diffusion coefficient
Definition at line 1540 of file ODECont.cpp.
References solutionCorrection::dim, and gsl_vector_get_inner_product().
Referenced by getPhaseDiffusion(), and periodicOrbitCont::periodicOrbitCont().
getPhaseDiffusion() [2/2]
double getPhaseDiffusion (const std::vector< gsl_matrix *> * Qs, const std::vector< gsl_matrix *> * Mts, const gsl_vector * vLeft, const gsl_vector * vRight, const double dt)
Calculate phase diffusion coefficient from M(t, s) and Q(s).
Calculate phase diffusion coefficient from time series of fundamental matrices and of diffusion matrices , with .
Parameters
[in] Qs Time series of diffusion matrices.
[in] Mts Time series of fundamental matrices.
[in] vLeft Left vector on which to project.
[in] vRight Right vector on which to project.
[in] dt Time step of integration.
Returns
Phase diffusion coefficient
Definition at line 1577 of file ODECont.cpp.
References solutionCorrection::dim, getCovarianceMatrix(), getPhaseDiffusion(), and nt.
normalizeFloquet() [1/2]
void normalizeFloquet (periodicOrbitCont * track, const gsl_vector_complex * FloquetExp, gsl_matrix_complex * eigVecLeft, gsl_matrix_complex * eigVecRight)
Normalize the Floquet vectors for the left one tangent to the flow to have the same magnitude as the vector field given a periodic orbit continuation problem.
Parameters
[in] track Continuation problem.
[in] FloquetExp Floquet exponents.
[out] eigVecLeft Left Floquet vector.
[out] eigVecRight Right Floquet vector.
Definition at line 1671 of file ODECont.cpp.
References solutionCorrection::dim, modelBase::field, periodicOrbitCont::getCurrentState(), solutionCorrection::getDim(), periodicOrbitTrack::linMod, and fundamentalMatrixModel::mod.
Referenced by getFloquet(), and periodicOrbitCont::periodicOrbitCont().
normalizeFloquet() [2/2]
void normalizeFloquet (const gsl_vector * stateCont, vectorField * field, const gsl_vector_complex * FloquetExp, gsl_matrix_complex * eigVecLeft, gsl_matrix_complex * eigVecRight)
Normalize the Floquet vectors for the left one tangent to the flow to have the same magnitude as the vector field given a state and a vector field.
Parameters
[in] stateCont State at which the Floquet analysis is performed.
[in] field Vector field for which the Floquet analysis is performed.
[in] FloquetExp Floquet exponents.
[out] eigVecLeft Left Floquet vector.
[out] eigVecRight Right Floquet vector.
Definition at line 1704 of file ODECont.cpp.
References solutionCorrection::dim, vectorField::evalField(), gsl_vector_complex_get_inner_product(), gsl_vector_complex_get_norm(), gsl_vector_complex_min_index(), gsl_vector_complex_scale_real(), and gsl_vector_get_norm().
sortSpectrum()
void sortSpectrum (gsl_vector_complex * eigValLeft, gsl_matrix_complex * eigVecLeft, gsl_vector_complex * eigValRight, gsl_matrix_complex * eigVecRight)
Sort by left and right eigenvalues and eigenvectors by largest largest maginitude of eigenvalue.
Parameters
[in,out] eigValLeft Left eigenvalues.
[in,out] eigVecLeft Left eigenvectors.
[in,out] eigValRight Right eigenvalues.
[in,out] eigVecRight Right eigenvectors.
Sort right eigenvalues and vectors by decreasing real parts Get real part of right eigenvalues
Get sort by increasing real part
Reverse to decreasing real part
Apply sort to right eigenvalues
Apply sort to right eigenvectors (column by column)
Sort left vectors by correspondance to for counterparts (since different eigenvalues may have the same magnitude).
Save left eigen elements
Select left eigenvalue ev
Get distance from eigenvalue |vr - conj(vl)|
Get index idx of right eigenvalue with minimum distance to left one
Move left eigenvalue ev to idx
Move left eigenvector ev to idx
Free
Definition at line 1806 of file ODECont.cpp.
References solutionCorrection::dim, gsl_permute_matrix_complex(), and gsl_vector_complex_min_index().
Referenced by getFloquet(), and periodicOrbitCont::periodicOrbitCont().
writeFloquet()
void writeFloquet (periodicOrbitCont * track, const gsl_vector * state, const gsl_vector_complex * FloquetExp, const gsl_matrix_complex * eigVecLeft, const gsl_matrix_complex * eigVecRight, FILE * streamState, FILE * streamExp, FILE * streamVecLeft, FILE * streamVecRight, const char * fileFormat, const bool verbose)
Write Floquet eigenvalues and left and right eigenvectors.
Parameters
[in] track Periodic ontinuation problem.
[in] state State vector on orbit.
[in] FloquetExp Floquet exponents.
[in] eigVecLeft Left Floquet vectors.
[in] eigVecRight Right Floquet vectors.
[out] streamState Stream in which to write state.
[out] streamExp Stream in which to write Floquet exponents.
[out] streamVecLeft Stream in which to write left Floquet vectors.
[out] streamVecRight Stream in which to write right Floquet vectors.
[in] fileFormat Format (bin/txt) of output files.
[in] verbose Print results to standard output.
Definition at line 1761 of file ODECont.cpp.
Referenced by periodicOrbitCont::periodicOrbitCont().