ergoPack: fixedPointCorr Class Reference
fixedPointCorr Class Reference
Continuation
Newton correction of fixed points.
#include <ODECont.hpp>
Public Member Functions
fixedPointCorr (vectorField *field_, linearField *Jac, const double epsDist_, const double epsStepCorrSize_, const size_t maxIter_, const bool verbose_=false)
Constructor assigning a linearized model and parameters.
void findSolution (const gsl_vector *init)
Find fixed point using Newton-Raphson method.
void updateTargetCorr ()
Update targetCorr.
void getSystemCorr ()
Get matrix of the linear system to be solved for correction.
Public Member Functions inherited from fixedPointTrack
fixedPointTrack (vectorField *field_, linearField *Jac, const double epsDist_, const double epsStepCorrSize_, const size_t maxIter_, const bool verbose_=false)
Constructor assigning a linearized model and parameters.
void setCurrentState ()
Set current state.
void setCurrentState (const gsl_vector *init)
Set current state.
void setInitialState (const gsl_vector *init)
Set initial state.
void initialize ()
Initialize.
void getStabilityMatrix (gsl_matrix *matrix)
Get the Jacobian of the solution.
Public Member Functions inherited from solutionCorrection
solutionCorrection (const double epsDist_, const double epsStepCorrSize_, const size_t maxIter_, const bool verbose_=false)
Constructor assigning a linearized model and parameters.
size_t getDim ()
Return the dimension of the problem.
size_t getNumIter ()
Return the number of iterations used for tracking.
double getDist ()
Return the last distance to the targetCorr.
double getStepCorrSize ()
Return the size of the last stepCorr.
bool hasConverged ()
Return the flag for the convergence of the tracking.
void NewtonStep ()
Perform a Newton step to find a fixed point.
void applyCorr (const double damping=1)
Correct with the stepCorr obtained from the Newton stepCorr.
virtual ~solutionCorrection ()
Destructor.
virtual void getCurrentState (gsl_vector *current_)
Get current state of tracking.
virtual void getInitialState (gsl_vector *initial_)
Get initial state of tracking.
void setInitialStateToCurrent ()
Set initial state to current state.
Additional Inherited Members
Protected Attributes inherited from fixedPointTrack
vectorField *const field
Nonlinear vector field.
linearField *const Jacobian
Linearized vector field.
Protected Attributes inherited from solutionCorrection
size_t dim
Dimension of the problem.
const double epsDist
Tolerance in the distance to zero.
const double epsStepCorrSize
Tolerance in the size of stepCorr.
const size_t maxIter
Maximum number of iterations.
double errDist
Distance to zero.
double errStepCorrSize
Size of stepCorr.
gsl_vector * stepCorr
StepCorr correcting the solution.
gsl_vector * targetCorr
TargetCorr vector.
size_t numIter
Number of iterations.
bool converged
Flag for convergence of the tracking.
gsl_matrix * S
Matrix of linear system to solve (workspace).
gsl_vector * current
Current state of tracking.
gsl_vector * initial
Initial state of tracking.
bool verbose
Verbose mode.
Detailed Description
Newton correction of fixed points.
Definition at line 167 of file ODECont.hpp.
Member Function Documentation
findSolution()
void fixedPointCorr::findSolution (const gsl_vector * init)
Find fixed point using Newton-Raphson method.
Parameters
[in] init Vector from which to start tracking.
Update state x of model and Jacobian J(x) to current state
Update the convergence flag.
Definition at line 207 of file ODECont.cpp.
References solutionCorrection::applyCorr(), solutionCorrection::converged, solutionCorrection::epsDist, solutionCorrection::epsStepCorrSize, solutionCorrection::errDist, solutionCorrection::errStepCorrSize, gsl_vector_get_norm(), solutionCorrection::maxIter, solutionCorrection::NewtonStep(), solutionCorrection::numIter, solutionCorrection::setCurrentState(), solutionCorrection::setInitialState(), solutionCorrection::stepCorr, solutionCorrection::targetCorr, solutionCorrection::updateTargetCorr(), and solutionCorrection::verbose.
getSystemCorr()
void fixedPointCorr::getSystemCorr () virtual
Get matrix of the linear system to be solved.
Implements fixedPointTrack.
Definition at line 177 of file ODECont.cpp.
References solutionCorrection::S.
updateTargetCorr()
void fixedPointCorr::updateTargetCorr () virtual
Update targetCorr vector for fixed point tracking.
Implements fixedPointTrack.
Definition at line 189 of file ODECont.cpp.
References solutionCorrection::current, solutionCorrection::targetCorr, and solutionCorrection::verbose.
The documentation for this class was generated from the following files:
include/ODECont.hpp
src/ODECont.cpp