ergoPack: periodicOrbitTrack Class Reference
periodicOrbitTrack Class Reference abstract
Continuation
Abstract class Newton correction of periodic orbits.
#include <ODECont.hpp>
Public Member Functions
periodicOrbitTrack (fundamentalMatrixModel *linMod_, const double epsDist_, const double epsStepCorrSize_, const size_t maxIter_, const double intStepCorr_, const size_t numShoot_=1, const bool verbose_=false)
Constructor assigning a linearized model and parameters.
size_t getNumShoot ()
Get number of shoots.
virtual void getCurrentState (gsl_vector *current_)
Get current state of tracking.
virtual void setCurrentState ()
Set current state.
virtual void setCurrentState (const gsl_vector *init)
Set current state.
virtual void getInitialState (gsl_vector *initial_)
Get initial state of tracking.
virtual void setInitialState (const gsl_vector *init)
Set initial state.
void initialize ()
Initialize.
void getStabilityMatrix (gsl_matrix *matrix)
Get the fundamental matrix of the solution.
virtual void updateTargetCorr ()=0
Update targetCorr.
virtual void getSystemCorr ()=0
Get matrix of the linear system to be solved for correction.
Public Member Functions inherited from solutionCorrection
solutionCorrection (const double epsDist_, const double epsStepCorrSize_, const size_t maxIter_, const bool verbose_=false)
Constructor assigning a linearized model and parameters.
size_t getDim ()
Return the dimension of the problem.
size_t getNumIter ()
Return the number of iterations used for tracking.
double getDist ()
Return the last distance to the targetCorr.
double getStepCorrSize ()
Return the size of the last stepCorr.
bool hasConverged ()
Return the flag for the convergence of the tracking.
void NewtonStep ()
Perform a Newton step to find a fixed point.
void applyCorr (const double damping=1)
Correct with the stepCorr obtained from the Newton stepCorr.
virtual ~solutionCorrection ()
Destructor.
void setInitialStateToCurrent ()
Set initial state to current state.
Public Attributes
fundamentalMatrixModel *const linMod
Full and linearized model.
Protected Member Functions
virtual void adaptTimeToPeriod ()
Adapt time step and number of time steps to shooting strategy.
virtual void adaptTimeToPeriod (const double T)
Adapt time step and number of time steps for a give period.
Protected Attributes
const double intStepCorr
Int. time stepCorr (to be adap. to period).
size_t nt
Total number of integration step.
gsl_vector_uint * ntShoot
Number of integration step per shoot.
double dt
Adapted time step.
const size_t numShoot
Number of shoots to correct/predict orbit.
Protected Attributes inherited from solutionCorrection
size_t dim
Dimension of the problem.
const double epsDist
Tolerance in the distance to zero.
const double epsStepCorrSize
Tolerance in the size of stepCorr.
const size_t maxIter
Maximum number of iterations.
double errDist
Distance to zero.
double errStepCorrSize
Size of stepCorr.
gsl_vector * stepCorr
StepCorr correcting the solution.
gsl_vector * targetCorr
TargetCorr vector.
size_t numIter
Number of iterations.
bool converged
Flag for convergence of the tracking.
gsl_matrix * S
Matrix of linear system to solve (workspace).
gsl_vector * current
Current state of tracking.
gsl_vector * initial
Initial state of tracking.
bool verbose
Verbose mode.
Detailed Description
Abstract class Newton correction of periodic orbits.
Definition at line 281 of file ODECont.hpp.
Member Function Documentation
adaptTimeToPeriod() [1/2]
void periodicOrbitTrack::adaptTimeToPeriod () protected virtual
Adapt time step and number of time steps to shooting strategy.
Definition at line 698 of file ODECont.cpp.
References solutionCorrection::current, solutionCorrection::dim, and numShoot.
adaptTimeToPeriod() [2/2]
void periodicOrbitTrack::adaptTimeToPeriod (const double T) protected virtual
Adapt time step and number of time steps to shooting strategy.
Parameters
[in] T Period to adapt time to.
Definition at line 717 of file ODECont.cpp.
References solutionCorrection::converged, solutionCorrection::current, solutionCorrection::dim, dt, nt, and numShoot.
getCurrentState()
void periodicOrbitTrack::getCurrentState (gsl_vector * current_) virtual
Get current state of tracking. If current_->size == dim + 1, return x(0), T else if current_->size == dim*numShoot + 1, return x(0), ..., x(numShoot-1), T
Parameters
[in] current_ Vector in which to copy the current state.
Reimplemented from solutionCorrection.
Reimplemented in periodicOrbitCont.
Definition at line 509 of file ODECont.cpp.
References solutionCorrection::current, solutionCorrection::dim, and numShoot.
getInitialState()
void periodicOrbitTrack::getInitialState (gsl_vector * initial_) virtual
Get initial state of tracking. If initial_->size == dim + 1, return x(0), T else if initial_->size == dim*numShoot + 1, return x(0), ..., x(numShoot-1), T
Parameters
[in] initial_ Vector in which to copy the initial state.
Reimplemented from solutionCorrection.
Reimplemented in periodicOrbitCont.
Definition at line 537 of file ODECont.cpp.
References solutionCorrection::dim, solutionCorrection::initial, and numShoot.
getStabilityMatrix()
void periodicOrbitTrack::getStabilityMatrix (gsl_matrix * matrix) virtual
Get fundamental matrix of the current state.
Parameters
[in] matrix Matrix in which to copy the fundamental matrix.
Implements solutionCorrection.
Definition at line 749 of file ODECont.cpp.
References dt, nt, and solutionCorrection::setCurrentState().
Referenced by getFloquet().
initialize()
void periodicOrbitTrack::initialize () virtual
Initialize.
Implements solutionCorrection.
Definition at line 684 of file ODECont.cpp.
References solutionCorrection::current, solutionCorrection::initial, and solutionCorrection::setCurrentState().
setCurrentState() [1/2]
void periodicOrbitTrack::setCurrentState () virtual
Set current state of the model and fundamental matrix
Implements solutionCorrection.
Reimplemented in periodicOrbitCont.
Definition at line 562 of file ODECont.cpp.
References solutionCorrection::current, solutionCorrection::dim, and solutionCorrection::verbose.
setCurrentState() [2/2]
void periodicOrbitTrack::setCurrentState (const gsl_vector * init) virtual
Set current state of the problem together with that of the model.
Parameters
[in] init Initial state.
Implements solutionCorrection.
Reimplemented in periodicOrbitCont.
Definition at line 582 of file ODECont.cpp.
References solutionCorrection::current, solutionCorrection::dim, dt, numShoot, and solutionCorrection::setCurrentState().
setInitialState()
void periodicOrbitTrack::setInitialState (const gsl_vector * init) virtual
Set initial state of the problem together with that of the model.
Parameters
[in] init Initial state.
Implements solutionCorrection.
Reimplemented in periodicOrbitCont.
Definition at line 633 of file ODECont.cpp.
References solutionCorrection::current, solutionCorrection::dim, dt, solutionCorrection::initial, solutionCorrection::initialize(), and numShoot.
The documentation for this class was generated from the following files:
include/ODECont.hpp
src/ODECont.cpp