ergoPack: fixedPointCont Class Reference
fixedPointCont Class Reference
Continuation of fixed points.
#include <ODECont.hpp>
Public Member Functions
fixedPointCont (vectorField *field_, linearField *Jac, const double epsDist_, const double epsStepSize_, const size_t maxIter_, const bool verbose_=false)
Constructor assigning a linearized model and parameters.
~fixedPointCont ()
Default destructor.
void correct (const gsl_vector *init)
Correction of initial state.
void correct ()
Correction after prediction.
void updateTargetCorr ()
Update correction target vector for fixed point tracking.
void continueStep (const double contStep, const gsl_vector *init)
Perform one step (correct. + predict.) of peudo-arc. cont.
void continueStep (const double contStep)
Perform one step (correct. + predict.) of peudo-arc. cont.
void getSystemCorr ()
Get matrix of the linear system to be solved for correction.
void getSystemPred ()
Get matrix of the linear system to be solved for prediction.
Public Member Functions inherited from fixedPointTrack
fixedPointTrack (vectorField *field_, linearField *Jac, const double epsDist_, const double epsStepCorrSize_, const size_t maxIter_, const bool verbose_=false)
Constructor assigning a linearized model and parameters.
void setCurrentState ()
Set current state.
void setCurrentState (const gsl_vector *init)
Set current state.
void setInitialState (const gsl_vector *init)
Set initial state.
void initialize ()
Initialize.
void getStabilityMatrix (gsl_matrix *matrix)
Get the Jacobian of the solution.
Public Member Functions inherited from solutionCorrection
solutionCorrection (const double epsDist_, const double epsStepCorrSize_, const size_t maxIter_, const bool verbose_=false)
Constructor assigning a linearized model and parameters.
size_t getDim ()
Return the dimension of the problem.
size_t getNumIter ()
Return the number of iterations used for tracking.
double getDist ()
Return the last distance to the targetCorr.
double getStepCorrSize ()
Return the size of the last stepCorr.
bool hasConverged ()
Return the flag for the convergence of the tracking.
void NewtonStep ()
Perform a Newton step to find a fixed point.
void applyCorr (const double damping=1)
Correct with the stepCorr obtained from the Newton stepCorr.
virtual ~solutionCorrection ()
Destructor.
virtual void getCurrentState (gsl_vector *current_)
Get current state of tracking.
virtual void getInitialState (gsl_vector *initial_)
Get initial state of tracking.
void setInitialStateToCurrent ()
Set initial state to current state.
Public Member Functions inherited from solutionCont
solutionCont (const size_t verboseCont_)
Constructor.
~solutionCont ()
Default destructor.
void applyPredict (const double contStep, gsl_vector *current)
Update state after prediction.
void predict (gsl_matrix *S)
Prediction Newton-Raphson step.
Additional Inherited Members
Protected Attributes inherited from fixedPointTrack
vectorField *const field
Nonlinear vector field.
linearField *const Jacobian
Linearized vector field.
Protected Attributes inherited from solutionCorrection
size_t dim
Dimension of the problem.
const double epsDist
Tolerance in the distance to zero.
const double epsStepCorrSize
Tolerance in the size of stepCorr.
const size_t maxIter
Maximum number of iterations.
double errDist
Distance to zero.
double errStepCorrSize
Size of stepCorr.
gsl_vector * stepCorr
StepCorr correcting the solution.
gsl_vector * targetCorr
TargetCorr vector.
size_t numIter
Number of iterations.
bool converged
Flag for convergence of the tracking.
gsl_matrix * S
Matrix of linear system to solve (workspace).
gsl_vector * current
Current state of tracking.
gsl_vector * initial
Initial state of tracking.
bool verbose
Verbose mode.
Protected Attributes inherited from solutionCont
gsl_vector * stepPred
Step of prediction.
gsl_vector * targetPred
(0, ..., 0, 1) vector for prediction
const bool verboseCont
Verbose mode.
Detailed Description
Continuation of fixed points.
Definition at line 228 of file ODECont.hpp.
Member Function Documentation
continueStep() [1/2]
void fixedPointCont::continueStep (const double contStep, const gsl_vector * init)
Perform one step (correction + prediction) of pseudo-arclength continuation from initial state.
Parameters
[in] contStep Continuation step size.
[in] init Vector from which to start tracking.
Definition at line 447 of file ODECont.cpp.
References solutionCorrection::setInitialState().
continueStep() [2/2]
void fixedPointCont::continueStep (const double contStep)
Perform one step (correction + prediction) of pseudo-arclength continuation from current step.
Parameters
[in] contStep Continuation step size.
Definition at line 465 of file ODECont.cpp.
References solutionCorrection::current, solutionCorrection::numIter, solutionCorrection::S, solutionCorrection::setCurrentState(), and solutionCorrection::verbose.
correct() [1/2]
void fixedPointCont::correct (const gsl_vector * init)
Correct initial state.
Definition at line 364 of file ODECont.cpp.
References solutionCorrection::setInitialState().
correct() [2/2]
void fixedPointCont::correct ()
Correct prediction by pseudo-arclenght continuation and Newton-Raphson.
Update state of model and Jacobian J(x) to current state
Update the convergence flag.
Definition at line 380 of file ODECont.cpp.
References solutionCorrection::applyCorr(), solutionCorrection::converged, solutionCorrection::current, solutionCorrection::epsDist, solutionCorrection::epsStepCorrSize, solutionCorrection::errDist, solutionCorrection::errStepCorrSize, gsl_vector_get_norm(), solutionCorrection::maxIter, solutionCorrection::NewtonStep(), solutionCorrection::numIter, solutionCorrection::setCurrentState(), solutionCorrection::stepCorr, solutionCorrection::targetCorr, solutionCorrection::updateTargetCorr(), and solutionCorrection::verbose.
getSystemCorr()
void fixedPointCont::getSystemCorr () virtual
Get matrix of the linear system to be solved for correction.
Implements fixedPointTrack.
Definition at line 313 of file ODECont.cpp.
References solutionCorrection::dim, and solutionCorrection::S.
getSystemPred()
void fixedPointCont::getSystemPred () virtual
Get matrix of the linear system to be solved for prediction.
Implements solutionCont.
Definition at line 332 of file ODECont.cpp.
References solutionCorrection::getSystemCorr().
updateTargetCorr()
void fixedPointCont::updateTargetCorr () virtual
Update correction target vector for fixed point tracking.
Implements fixedPointTrack.
Definition at line 344 of file ODECont.cpp.
References solutionCorrection::current, solutionCorrection::dim, solutionCorrection::targetCorr, and solutionCorrection::verbose.
The documentation for this class was generated from the following files:
include/ODECont.hpp
src/ODECont.cpp