ergoPack: periodicOrbitCorr Class Reference
periodicOrbitCorr Class Reference
Newton correction of periodic orbits.
#include <ODECont.hpp>
Public Member Functions
periodicOrbitCorr (fundamentalMatrixModel *linMod_, const double epsDist_, const double epsStepCorrSize_, const size_t maxIter_, const double intStepCorr_, const size_t numShoot_=1, const bool verbose_=false)
Constructor assigning a linearized model and parameters.
void updateTargetCorr ()
Update targetCorr.
void findSolution (const gsl_vector *init)
Find fixed point using Newton-Raphson method.
void getSystemCorr ()
Get matrix of the linear system to be solved for correction.
Public Member Functions inherited from periodicOrbitTrack
periodicOrbitTrack (fundamentalMatrixModel *linMod_, const double epsDist_, const double epsStepCorrSize_, const size_t maxIter_, const double intStepCorr_, const size_t numShoot_=1, const bool verbose_=false)
Constructor assigning a linearized model and parameters.
size_t getNumShoot ()
Get number of shoots.
virtual void getCurrentState (gsl_vector *current_)
Get current state of tracking.
virtual void setCurrentState ()
Set current state.
virtual void setCurrentState (const gsl_vector *init)
Set current state.
virtual void getInitialState (gsl_vector *initial_)
Get initial state of tracking.
virtual void setInitialState (const gsl_vector *init)
Set initial state.
void initialize ()
Initialize.
void getStabilityMatrix (gsl_matrix *matrix)
Get the fundamental matrix of the solution.
Public Member Functions inherited from solutionCorrection
solutionCorrection (const double epsDist_, const double epsStepCorrSize_, const size_t maxIter_, const bool verbose_=false)
Constructor assigning a linearized model and parameters.
size_t getDim ()
Return the dimension of the problem.
size_t getNumIter ()
Return the number of iterations used for tracking.
double getDist ()
Return the last distance to the targetCorr.
double getStepCorrSize ()
Return the size of the last stepCorr.
bool hasConverged ()
Return the flag for the convergence of the tracking.
void NewtonStep ()
Perform a Newton step to find a fixed point.
void applyCorr (const double damping=1)
Correct with the stepCorr obtained from the Newton stepCorr.
virtual ~solutionCorrection ()
Destructor.
void setInitialStateToCurrent ()
Set initial state to current state.
Additional Inherited Members
Public Attributes inherited from periodicOrbitTrack
fundamentalMatrixModel *const linMod
Full and linearized model.
Protected Member Functions inherited from periodicOrbitTrack
virtual void adaptTimeToPeriod ()
Adapt time step and number of time steps to shooting strategy.
virtual void adaptTimeToPeriod (const double T)
Adapt time step and number of time steps for a give period.
Protected Attributes inherited from periodicOrbitTrack
const double intStepCorr
Int. time stepCorr (to be adap. to period).
size_t nt
Total number of integration step.
gsl_vector_uint * ntShoot
Number of integration step per shoot.
double dt
Adapted time step.
const size_t numShoot
Number of shoots to correct/predict orbit.
Protected Attributes inherited from solutionCorrection
size_t dim
Dimension of the problem.
const double epsDist
Tolerance in the distance to zero.
const double epsStepCorrSize
Tolerance in the size of stepCorr.
const size_t maxIter
Maximum number of iterations.
double errDist
Distance to zero.
double errStepCorrSize
Size of stepCorr.
gsl_vector * stepCorr
StepCorr correcting the solution.
gsl_vector * targetCorr
TargetCorr vector.
size_t numIter
Number of iterations.
bool converged
Flag for convergence of the tracking.
gsl_matrix * S
Matrix of linear system to solve (workspace).
gsl_vector * current
Current state of tracking.
gsl_vector * initial
Initial state of tracking.
bool verbose
Verbose mode.
Detailed Description
Newton correction of periodic orbits.
Definition at line 355 of file ODECont.hpp.
Member Function Documentation
findSolution()
void periodicOrbitCorr::findSolution (const gsl_vector * init)
Find periodic orbit using Newton-Raphson method.
Parameters
[in] init Vector from which to start tracking.
Update state of model and Jacobian to current state and reinitizlize fundamental matrix to identity (after integration in updateTargetCorr).
Get targetCorr vector to and state of linearized model
Update state of model and Jacobian to current state and reinitizlize fundamental matrix to identity.
Update the convergence flag.
Definition at line 866 of file ODECont.cpp.
References solutionCorrection::applyCorr(), solutionCorrection::converged, solutionCorrection::current, solutionCorrection::dim, solutionCorrection::epsDist, solutionCorrection::epsStepCorrSize, solutionCorrection::errDist, solutionCorrection::errStepCorrSize, gsl_vector_get_norm(), solutionCorrection::maxIter, solutionCorrection::NewtonStep(), solutionCorrection::numIter, numShoot, solutionCorrection::setCurrentState(), solutionCorrection::setInitialState(), solutionCorrection::stepCorr, solutionCorrection::targetCorr, solutionCorrection::updateTargetCorr(), and solutionCorrection::verbose.
getSystemCorr()
void periodicOrbitCorr::getSystemCorr () virtual
Get matrix of the linear system to be solved.
Implements periodicOrbitTrack.
Definition at line 778 of file ODECont.cpp.
References solutionCorrection::current, solutionCorrection::dim, dt, numShoot, and solutionCorrection::S.
updateTargetCorr()
void periodicOrbitCorr::updateTargetCorr () virtual
Update targetCorr vector for periodic orbit tracking.
Integrate model for a period from the new current state after initializing the linear model to x(s) (no need to update the linear model here).
Implements periodicOrbitTrack.
Definition at line 823 of file ODECont.cpp.
References solutionCorrection::current, solutionCorrection::dim, dt, numShoot, solutionCorrection::targetCorr, and solutionCorrection::verbose.
The documentation for this class was generated from the following files:
include/ODECont.hpp
src/ODECont.cpp