ergoPack: polynomial1D Class Reference
polynomial1D Class Reference
Simulating
One-dimensional polynomial vector field.
#include <ODEFields.hpp>
Public Member Functions
polynomial1D (const size_t degree_)
Construction by allocating vector of coefficients.
polynomial1D (const gsl_vector *coeff_)
Construction by copying coefficients of polynomial.
~polynomial1D ()
void getParameters (gsl_vector *coeff_)
Return the coefficients of the polynomial field (should be allocated first).
void setParameters (const gsl_vector *coeff_)
Set parameters of the model.
void evalField (const gsl_vector *state, gsl_vector *field, const double t=0.)
Evaluate the linear vector field at a given state.
Public Member Functions inherited from vectorField
vectorField ()
Default onstructor.
vectorField (const param *p_)
Constructor.
virtual ~vectorField ()
Destructor.
virtual void getParameters (param *p_)
Return the parameters of the model.
virtual void setParameters (const param *p_)
Set parameters of the model.
Additional Inherited Members
Protected Attributes inherited from vectorField
param p
Parameters.
Detailed Description
One-dimensional polynomial vector field
Definition at line 29 of file ODEFields.hpp.
Constructor & Destructor Documentation
~polynomial1D()
polynomial1D::~polynomial1D () inline
Destructor freeing the matrix.
Definition at line 45 of file ODEFields.hpp.
Member Function Documentation
evalField()
void polynomial1D::evalField (const gsl_vector * state, gsl_vector * field, const double t = 0.) virtual
Evaluate the one-dimensional polynomial vector field at a given state.
Parameters
[in] state State at which to evaluate the vector field.
[out] field Vector resulting from the evaluation of the vector field.
[in] t Time.
Implements vectorField.
Definition at line 27 of file ODEFields.cpp.
Referenced by pitchforkField::pitchforkField(), pitchforkSubField::pitchforkSubField(), saddleNodeField::saddleNodeField(), setParameters(), transcriticalField::transcriticalField(), cuspField::~cuspField(), Hopf::~Hopf(), HopfCont::~HopfCont(), Lorenz63::~Lorenz63(), and Lorenz63Cont::~Lorenz63Cont().
The documentation for this class was generated from the following files:
include/ODEFields.hpp
src/ODEFields.cpp