ergoPack: transferSpectrum Class Reference
transferSpectrum Class Reference
Transfer operators
Transfer operator spectrum.
#include <transferSpectrum.hpp>
Public Member Functions
transferSpectrum (const int nev_, const transferOperator *transferOp_, const configAR cfgAR)
Constructor allocating for nev_ eigenvalues and vectors.
~transferSpectrum ()
Destructor desallocating.
void getSpectrumForward ()
Get spectrum of forward transition matrices.
void getSpectrumBackward ()
Get spectrum of backward transition matrices.
void getSpectrum ()
Get spectrum of both forward and backward transition matrices.
gsl_vector * getConditionNumbers ()
Get condition number associated with each eigenvalues.
void sort ()
Sort by largest magnitude.
void makeBiorthonormal ()
Make set of forward and backward eigenvectors biorthonormal.
gsl_vector_complex * getWeights (const gsl_vector *f, const gsl_vector *g)
Get weights for two observables.
void writeEigValForward (const char *EigValForwardFile, const char *fileFormat="txt") const
Write forward eigenvalues.
void writeEigValBackward (const char *EigValBackwardFile, const char *fileFormat="txt") const
Write backward eigenvalues.
void writeSpectrumForward (const char *EigValForwardFile, const char *EigVecForwardFile, const char *fileFormat) const
Write forward eigenvalues and eigenvectors.
void writeSpectrumBackward (const char *EigValBackwardFile, const char *EigVecBackwardFile, const char *fileFormat) const
Write backward eigenvalues and eigenvectors.
void writeSpectrum (const char *EigValForwardFile, const char *EigVecForwardFile, const char *EigValBackwardFile, const char *EigVecBackwardFile, const char *fileFormat) const
Write forward and backward eigenvalues and eigenvectors.
size_t getN () const
Get number of grid boxes.
bool isSorted () const
Get whether forward and backward eigenvalues and vectors are sorted.
int getNev () const
Get number of eigen values and vectors to look for.
configAR getConfig () const
Get configuration.
void setConfig (const configAR newConfig)
Set configuration.
Public Attributes
gsl_vector_complex * EigValForward
Eigenvalues of forward transition matrix.
gsl_vector_complex * EigValBackward
Eigenvalues of backward transition matrix.
gsl_matrix_complex * EigVecForward
Eigenvectors of forward transition matrix.
gsl_matrix_complex * EigVecBackward
Eigenvectors of backward transition matrix.
ARNonSymStdEig< double, gsl_spmatrix2AR > EigProbForward
Eigen value problem for forward transition matrix.
ARNonSymStdEig< double, gsl_spmatrix2AR > EigProbBackward
Eigen value problem for backward transition matrix.
Detailed Description
Class used to calculate the spectrum of forward and backward transition matrices of a transferOperator object.
Definition at line 63 of file transferSpectrum.hpp.
Constructor & Destructor Documentation
transferSpectrum()
transferSpectrum::transferSpectrum (const int nev_, const transferOperator * transferOp_, const configAR cfgAR = defaultCfgAR)
Constructor allocating space for a given number of eigenvalues and vectors for a given transferOperator.
Parameters
[in] nev_ Number of eigenvalues and eigenvectors for which to allocate.
[in] transferOp_ Pointer to the transferOperator on which to solve the eigen problem.
[in] cfgAR Configuration data used by ARPACK++ for the eigen problem.
Definition at line 30 of file transferSpectrum.cpp.
~transferSpectrum()
transferSpectrum::~transferSpectrum ()
Destructor desallocates.
Free memory for forward eigenvalues and eigenvectors
Free memory for backward eigenvalues and eigenvectors
Definition at line 42 of file transferSpectrum.cpp.
References EigValBackward, EigValForward, EigVecBackward, and EigVecForward.
Member Function Documentation
getConditionNumbers()
gsl_vector * transferSpectrum::getConditionNumbers ()
Get condition numbers associated with each eigenvalue. The condition number associated with eigenvalue is , where and are the forward and backward (adjoint) eigenvectors, respectively and norm is for w.r.t the initial distribution. The condition number is equal to the inverse of the cosine of the angle between the two vectors and gives a measure of the nonnormality associated with a particular pair of eigenvectors.
Returns
Condition numbers associated with each pair of eigenvectors.
Get norms of eigenvectors
Get norm of forward eigenvector
Get norm of backward eigenvector.
Divide by their inner product (in case not made biorthonormal)
Set condition number
Definition at line 160 of file transferSpectrum.cpp.
References EigVecBackward, EigVecForward, gsl_vector_complex_get_inner_product(), gsl_vector_complex_get_norm(), and transferOperator::initDist.
getSpectrum()
void transferSpectrum::getSpectrum ()
Get spectrum of transfer operator, including the complex eigenvalues, the left eigenvectors of the forward transition matrix and the right eigenvectors of the backward transitioin matrix. The vectors of eigenvalues and eigenvectors should not be preallocated.
Get spectrum of forward transition matrix
Get spectrum of backward transition matrix
Definition at line 134 of file transferSpectrum.cpp.
References getSpectrumBackward(), and getSpectrumForward().
getSpectrumBackward()
void transferSpectrum::getSpectrumBackward ()
Get right eigenvectors of transition matrix.
In the stationary case, the adjoint eigenvectors can be calculated as left eigenvectors of the forward transition matrix divided by the stationary distribution
Get eigenvalues and vectors of backward transition matrix
Definition at line 109 of file transferSpectrum.cpp.
References EigProbBackward, EigValBackward, EigVecBackward, getSpectrumAR(), and transferOperator::P.
Referenced by getSpectrum(), and main().
getSpectrumForward()
void transferSpectrum::getSpectrumForward ()
Get left eigenvectors of transition matrix.
Get transpose of transition matrix in CCS Transposing is trivial since the transition matrix is in CRS format. However, it is more secure to avoid directly changing the type of the transition matrix.
Solve eigen value problem using user-defined ARPACK++
Divide eigenvectors (real and imaginary parts) by stationary distribution
Definition at line 66 of file transferSpectrum.cpp.
References EigProbForward, EigValForward, EigVecForward, getSpectrumAR(), and transferOperator::P.
Referenced by getSpectrum(), and main().
getWeights()
gsl_vector_complex * transferSpectrum::getWeights (const gsl_vector * f, const gsl_vector * g)
Get weights associated with the projection of two observables on the backward and forward eigenvectors, respectively, i.e. .
Parameters
[in] f Vector representing the first observable, projected on the backward eigenvectors.
[in] g Vector representing the second observable, projected on the forward eigenvectors.
Returns
Weights associated with each pair of eigenvectors for the two observables.
Definition at line 206 of file transferSpectrum.cpp.
References EigVecBackward, EigVecForward, gsl_vector_complex_get_inner_product(), gsl_vector_complex_memcpy_real(), and transferOperator::initDist.
makeBiorthonormal()
void transferSpectrum::makeBiorthonormal ()
Make set of forward and backward eigenvectors biorthonormal.
Test that both forward and backward eigen problems have been solved and that eigenvalues and eigenvectors have been sorted.
Normalize backward eigenvectors by the scalar product with forward eigenvectors to make biorthonormal set.
Get inner product of forward and backward eigenvectors
Divide backward eigenvector by conjugate of inner product
Definition at line 327 of file transferSpectrum.cpp.
References EigValBackward, EigValForward, EigVecBackward, EigVecForward, gsl_vector_complex_get_inner_product(), and sort().
Referenced by main().
sort()
void transferSpectrum::sort ()
Sort by largest maginitude.
Test that both forward and backward eigen problems have been solved.
Sort forward eigenvalues by decreasing absolute value
Sort backward vectors by correspondance to forward counterparts (since different eigenvalues may have the same magnitude).
Get distance from eigenvalue
Sort backward eigenvalue and eigenvector
Free
Mark that sorting has been performed
Definition at line 256 of file transferSpectrum.cpp.
References EigValBackward, EigValForward, EigVecBackward, EigVecForward, gsl_permute_matrix_complex(), gsl_vector_complex_abs(), and gsl_vector_complex_min_index().
Referenced by makeBiorthonormal().
writeEigValBackward()
void transferSpectrum::writeEigValBackward (const char * EigValBackwardFile, const char * fileFormat = "txt") const
Write eigenvalues and of backward transition matrix.
Parameters
[in] EigValBackwardFile File name of the file to print backward eigenvalues.
[in] fileFormat String "bin" or "txt" for the output type.
Returns
Exit status.
Open files back backward
Write backward
Close
Definition at line 408 of file transferSpectrum.cpp.
References EigValBackward, and writeSpectrumAR().
writeEigValForward()
void transferSpectrum::writeEigValForward (const char * EigValForwardFile, const char * fileFormat = "txt") const
Write eigenvalues of forward transition matrix.
Parameters
[in] EigValForwardFile File name of the file to print forward eigenvalues.
[in] fileFormat String "bin" or "txt" for the output type.
Returns
Exit status.
Open files for forward
Write forward
Close
Definition at line 379 of file transferSpectrum.cpp.
References EigValForward, and writeSpectrumAR().
writeSpectrum()
void transferSpectrum::writeSpectrum (const char * EigValForwardFile, const char * EigVecForwardFile, const char * EigValBackwardFile, const char * EigVecBackwardFile, const char * fileFormat = "txt") const
Write complex eigenvalues and eigenvectors of forward and backward transition matrices.
Parameters
[in] EigValForwardFile File name of the file to print forward eigenvalues.
[in] EigVecForwardFile File name of the file to print forward eigenvectors.
[in] EigValBackwardFile File name of the file to print backward eigenvalues.
[in] EigVecBackwardFile File name of the file to print backward eigenvectors.
[in] fileFormat String "bin" or "txt" for the output type.
Returns
Exit status.
Write forward eigenvalues and eigenvectors
Write backward eigenvalues and eigenvectors
Definition at line 517 of file transferSpectrum.cpp.
References fileFormat, writeSpectrumBackward(), and writeSpectrumForward().
writeSpectrumBackward()
void transferSpectrum::writeSpectrumBackward (const char * EigValBackwardFile, const char * EigVecBackwardFile, const char * fileFormat = "txt") const
Write eigenvalues and eigenvectors of backward transition matrix.
Parameters
[in] EigValBackwardFile File name of the file to print backward eigenvalues.
[in] EigVecBackwardFile File name of the file to print backward eigenvectors.
[in] fileFormat String "bin" or "txt" for the output type.
Returns
Exit status.
Open files back backward
Write backward
Close
Definition at line 476 of file transferSpectrum.cpp.
References EigValBackward, EigVecBackward, fileFormat, and writeSpectrumAR().
Referenced by main(), and writeSpectrum().
writeSpectrumForward()
void transferSpectrum::writeSpectrumForward (const char * EigValForwardFile, const char * EigVecForwardFile, const char * fileFormat = "txt") const
Write eigenvalues and eigenvectors of forward transition matrix.
Parameters
[in] EigValForwardFile File name of the file to print forward eigenvalues.
[in] EigVecForwardFile File name of the file to print forward eigenvectors.
[in] fileFormat String "bin" or "txt" for the output type.
Returns
Exit status.
Open files for forward
Write forward
Close
Definition at line 438 of file transferSpectrum.cpp.
References EigValForward, EigVecForward, fileFormat, and writeSpectrumAR().
Referenced by main(), and writeSpectrum().
The documentation for this class was generated from the following files:
include/transferSpectrum.hpp
src/transferSpectrum.cpp