ergoPack: modelStochastic Class Reference
modelStochastic Class Reference
Simulation
Numerical stochastic model class.
#include <SDESolvers.hpp>
Public Member Functions
modelStochastic (vectorField *field_, vectorFieldStochastic *stocField_, numericalSchemeStochastic *scheme_)
Constructor assigning a vector field, a numerical scheme and a stochastic vector field and setting initial state to origin.
modelStochastic (vectorField *field_, vectorFieldStochastic *stocField_, numericalSchemeStochastic *scheme_, gsl_vector *initState)
Constructor assigning a vector field, a numerical scheme and a stochastic vector field and setting initial state.
~modelStochastic ()
Destructor freeing memory.
void stepForward ()
One time-step forward integration of the modelStochastic.
gsl_matrix * integrateForward (const double length, const double spinup, const size_t sampling)
Integrate the modelStochastic forward for a given period.
Protected Attributes
const size_t dim
Phase space dimension.
vectorField * field
Vector field.
vectorFieldStochastic * stocField
Stochastic vector field.
numericalSchemeStochastic * scheme
Numerical scheme.
gsl_vector * currentState
Current state.
Detailed Description
Numerical stochastic model class. A modelStochastic is defined by a vector field, a stochastic vector field and a numerical scheme. The current state of the modelStochastic is also recorded. Attention: the constructors do not copy the vector field and the numerical scheme given to them, so that any modification or freeing will affect the modelStochastic.
Definition at line 193 of file SDESolvers.hpp.
Member Function Documentation
gsl_matrix * modelStochastic::integrateForward (const double length, const double spinup, const size_t sampling)
Integrate the stochastic model forward for a given period.
Parameters
[in] length Duration of the integration.
[in] spinup Initial integration period to remove.
[in] sampling Time step at which to save states.
Returns
Matrix to record the states.
Definition at line 96 of file SDESolvers.cpp.
References currentState, dim, numericalSchemeStochastic::getTimeStep(), nt, scheme, and stepForward().
Referenced by main().
void modelStochastic::stepForward ()
Integrate one step forward the stochastic model with the numerical scheme.
Definition at line 79 of file SDESolvers.cpp.
References currentState, field, scheme, numericalSchemeStochastic::stepForward(), and stocField.
Referenced by integrateForward().
The documentation for this class was generated from the following files:
include/SDESolvers.hpp
src/SDESolvers.cpp