ergoPack: RegularGrid Class Reference
RegularGrid Class Reference
Gridding
Regular grid.
#include <ergoGrid.hpp>
Public Member Functions
RegularGrid (const gsl_vector_uint *nx_, const gsl_vector *gridLimitsLow, const gsl_vector *gridLimitsUp)
Construct a uniform rectangular grid with different dimensions.
RegularGrid (const size_t dim_, const size_t inx, const double gridLimitsLow, const double gridLimitsUp)
Construct a uniform rectangular grid with same dimensions.
RegularGrid (const gsl_vector_uint *nx_, const gsl_vector *nSTDLow, const gsl_vector *nSTDHigh, const gsl_matrix *states)
Construct a uniform rectangular grid adapted to time series.
RegularGrid (const size_t inx, const double nSTDLow, const double nSTDHigh, const gsl_matrix *states)
Construct a uniform rectangular grid with same dimensions adapted to time series.
~RegularGrid ()
Destructor desallocates memory for the grid boundaries.
int printGrid (const char *path, const char *dataFormat, const bool verbose) const
Print regular grid to file.
size_t getBoxMembership (const gsl_vector *state) const
Get membership of a state to a box.
void getBoxPosition (const size_t index, gsl_vector *position) const
Get center of position of grid box.
Public Member Functions inherited from CurvilinearGrid
CurvilinearGrid (const gsl_vector_uint *nx_)
Constructor allocating an empty grid.
CurvilinearGrid (const size_t dim_, const size_t inx)
Constructor allocating an empty grid with same dimensions.
~CurvilinearGrid ()
Public Member Functions inherited from Grid
Grid (const gsl_vector_uint *nx_)
Constructor allocating an empty grid.
Grid (const size_t dim_, const size_t inx)
Constructor allocating an empty grid with same dimensions.
virtual ~Grid ()
Destructor.
size_t getDim () const
Get state space dimension.
size_t getN () const
Get number of grid boxes.
Additional Inherited Members
Public Attributes inherited from CurvilinearGrid
gsl_vector_uint * nx
Number of grid boxes per dimension.
Public Attributes inherited from Grid
std::vector< gsl_vector * > * bounds
Grid box bounds for each dimension.
Protected Attributes inherited from Grid
const size_t dim
Number of dimensions.
const size_t N
Number of grid boxes.
Detailed Description
Definition at line 106 of file ergoGrid.hpp.
Constructor & Destructor Documentation
RegularGrid() [1/4]
RegularGrid::RegularGrid (const gsl_vector_uint * nx_, const gsl_vector * gridLimitsLow, const gsl_vector * gridLimitsUp)
Construct a uniform rectangular grid with specific bounds for each dimension.
Parameters
[in] nx_ Vector giving the number of boxes for each dimension.
[in] gridLimitsLow Vector giving the lower box limit for each dimension.
[in] gridLimitsUp Vector giving the upper box limit for each dimension.
Definition at line 61 of file ergoGrid.cpp.
RegularGrid() [2/4]
RegularGrid::RegularGrid (const size_t dim_, const size_t inx, const double dgridLimitsLow, const double dgridLimitsUp)
Construct a uniform rectangular grid with same bounds for each dimension.
Parameters
[in] dim_ Number of dimensions.
[in] inx Number of boxes, identically for each dimension.
[in] dgridLimitsLow Minimum box limit, identically for each dimension.
[in] dgridLimitsUp Maximum box limit, identically for each dimension.
Definition at line 80 of file ergoGrid.cpp.
RegularGrid() [3/4]
RegularGrid::RegularGrid (const gsl_vector_uint * nx_, const gsl_vector * nSTDLow, const gsl_vector * nSTDUp, const gsl_matrix * states)
Construct a uniform rectangular grid adapted to the time series.
Parameters
[in] nx_ Vector giving the number of boxes for each dimension.
[in] nSTDLow Vector giving the number of standard deviations to span away from the mean state from below.
[in] nSTDUp Vector giving the number of standard deviations to span away from the mean state from above.
[in] states Time series.
Definition at line 110 of file ergoGrid.cpp.
References Grid::bounds, Grid::dim, gridLimitsLow, gridLimitsUp, gsl_matrix_get_max(), gsl_matrix_get_mean(), gsl_matrix_get_min(), gsl_matrix_get_std(), and CurvilinearGrid::nx.
RegularGrid() [4/4]
RegularGrid::RegularGrid (const size_t inx, const double limLow, const double limUp, const gsl_matrix * states = NULL)
Construct a uniform rectangular grid with same dimensions adapted to the time series.
Parameters
[in] inx Number of boxes for each dimension.
[in] limLow Lower limit.
[in] limUp Upper limit.
[in] states Time series.
Definition at line 20 of file ergoGrid.cpp.
References Grid::dim, gridLimitsLow, and gridLimitsUp.
Member Function Documentation
getBoxMembership()
size_t RegularGrid::getBoxMembership (const gsl_vector * state) const virtual
Get membership to a grid box of a single realization.
Parameters
[in] state Vector of a single state.
Returns
Box index to which the state belongs.
Implements Grid.
Definition at line 278 of file ergoGrid.cpp.
References Grid::bounds, Grid::dim, Grid::N, CurvilinearGrid::nx, and ravel_multi_index().
getBoxPosition()
void RegularGrid::getBoxPosition (const size_t index, gsl_vector * position) const virtual
Get position of grid box.
Parameters
[in] index Index of box for which to get the position.
[out] position Position of the box.
Implements Grid.
Definition at line 386 of file ergoGrid.cpp.
References Grid::bounds, and Grid::dim.
printGrid()
int RegularGrid::printGrid (const char * path, const char * dataFormat = "%lf", const bool verbose = false) const virtual
Print the grid to file.
Parameters
[in] path Path to the file in which to print.
[in] dataFormat Format in which to print each element.
[in] verbose If true, also print to the standard output.
Returns
Status.
Check for printing errors
Implements Grid.
Definition at line 225 of file ergoGrid.cpp.
References Grid::bounds, Grid::dim, and verbose.
The documentation for this class was generated from the following files:
include/ergoGrid.hpp
src/ergoGrid.cpp