ergoPack: transferOperator Class Reference
transferOperator Class Reference
Transfer operators
Transfer operator class.
#include <transferOperator.hpp>
Public Member Functions
transferOperator (const size_t N_, const bool stationary_=false)
Empty constructor to allow manual building of transition matrix.
transferOperator (const gsl_matrix_uint *gridMem, const size_t N_, const bool stationary_=false)
Constructor from the membership matrix.
transferOperator (const gsl_matrix *initStates, const gsl_matrix *finalStates, const Grid *grid, const bool stationary_=false)
Constructor from initial and final states for a given grid.
transferOperator (const gsl_matrix *states, const Grid *grid, size_t tauStep)
Constructor from a long trajectory for a given grid and lag.
~transferOperator ()
Destructor.
int allocateDist ()
Allocate memory to the distributions.
size_t getN () const
Get number of grid boxes.
size_t getNFilled () const
Get number of filled grid boxes.
bool isStationary () const
Get whether stationary.
int printForwardTransition (const char *path, const char *fileFormat, const char *dataFormat)
Print forward transition matrix to file in coordinate format.
int printBackwardTransition (const char *path, const char *fileFormat, const char *dataFormat)
Print backward transition matrix to file in coordinate format.
int printInitDist (const char *path, const char *fileFormat, const char *dataFormat)
Print initial distribution to file.
int printFinalDist (const char *path, const char *fileFormat, const char *dataFormat)
Print final distribution to file.
int printMask (const char *path, const char *fileFormat, const char *dataFormat)
Print mask to file.
int scanForwardTransition (const char *path, const char *fileFormat)
Scan forward transition matrix to file in coordinate format.
int scanBackwardTransition (const char *path, const char *fileFormat)
Scan backward transition matrix to file in coordinate format.
int scanInitDist (const char *path, const char *fileFormat)
Scan initial distribution from file.
int scanFinalDist (const char *path, const char *fileFormat)
Scan final distribution from file.
int scanMask (const char *path, const char *fileFormat)
Scan mask from file.
void setInitDist (const gsl_vector *initDist_)
Manually change the initial distribution.
void setFinalDist (const gsl_vector *finalDist_)
Manually change the finalial distribution.
void setMask (const gsl_vector_uint *mask_)
Manually change the mask.
size_t addTransition (gsl_spmatrix *T, size_t box0, size_t boxf)
Add transition from pairs of initial and final grid boxes.
size_t getTransitionCountTriplet (const gsl_matrix_uint *gridMem, gsl_spmatrix *T)
Get triplet vector from membership matrix.
void buildFromTransitionCount (const gsl_spmatrix *T, const size_t nTraj)
Buid transition matrices from transition count matrix.
int filter (double tol)
Filtering of weak Markov states.
Public Attributes
gsl_spmatrix * P
Forward transition matrix (CRS)
gsl_spmatrix * Q
Backward transition matrix (CRS)
gsl_vector * initDist
Initial distribution.
gsl_vector * finalDist
Final distribution.
gsl_vector_uint * mask
Mask for empty boxes.
Detailed Description
Transfer operator class including the forward and backward transition matrices and the initial and final distributions calculated from data. The constructors are based on membership matrices with the first column giving the box to which belong the initial state of trajectories and the second column the box to which belong the final state of trajectories. The initial and final states can also be directly given as to matrices with each row giving a state. Finally, transferOperator can also be constructed from a single long trajectory and a given lag. Then, a membership vector is first calculated, assigning each realization to a box, from which the membership matrix can be calculated for the lag given.
The transition matrices are in CRS format, allowing for instant transpose to CCS for eigen problem using ARPACK++.
Definition at line 64 of file transferOperator.hpp.
Constructor & Destructor Documentation
transferOperator() [1/4]
transferOperator::transferOperator (const size_t N_, const bool stationary_ = false)
Empty constructor to allow manual building of transition matrix from the grid membership matrix without mask.
Parameters
[in] N_ Number of grid boxes.
[in] stationary_ Whether the system is stationary (in which case and no need to calculate the backward transition matrix).
Initialize distributions to zero
Definition at line 21 of file transferOperator.cpp.
References allocateDist(), finalDist, getMask(), initDist, and mask.
transferOperator() [2/4]
transferOperator::transferOperator (const gsl_matrix_uint * gridMem, const size_t N_, const bool stationary_ = false)
Construct transferOperator by calculating the forward and backward transition matrices and distributions from the grid membership matrix.
Parameters
[in] gridMem GSL grid membership matrix.
[in] N_ Number of grid boxes.
[in] stationary_ Whether the system is stationary (in which case and no need to calculate the backward transition matrix).
Definition at line 47 of file transferOperator.cpp.
References allocateDist(), getMask(), and mask.
transferOperator() [3/4]
transferOperator::transferOperator (const gsl_matrix * initStates, const gsl_matrix * finalStates, const Grid * grid, const bool stationary_ = false)
Construct transferOperator by calculating the forward and backward transition matrices and distributions from the initial and final states of trajectories.
Parameters
[in] initStates GSL matrix of initial states.
[in] finalStates GSL matrix of final states.
[in] grid Pointer to Grid object.
[in] stationary_ Whether the system is stationary (in which case and no need to calculate the backward transition matrix).
Definition at line 74 of file transferOperator.cpp.
References allocateDist(), getGridMemMatrix(), getMask(), and mask.
transferOperator() [4/4]
transferOperator::transferOperator (const gsl_matrix * states, const Grid * grid, size_t tauStep)
Construct transferOperator calculating the forward and backward transition matrices and distributions from a single long trajectory, for a given grid and lag.
Parameters
[in] states GSL matrix of states for each time step.
[in] grid Pointer to Grid object.
[in] tauStep Lag used to calculate the transitions.
Definition at line 107 of file transferOperator.cpp.
References allocateDist(), getGridMemMatrix(), getMask(), and mask.
~transferOperator()
transferOperator::~transferOperator ()
Destructor of transferOperator: desallocate all pointers.
Definition at line 131 of file transferOperator.cpp.
References finalDist, initDist, mask, P, and Q.
Member Function Documentation
addTransition()
size_t transferOperator::addTransition (gsl_spmatrix * T, size_t box0, size_t boxf)
Add transition to count matrix from a pair of initial and final grid boxes.
Parameters
[in] T Transition count matrix.
[in] box0 Initial box of transition.
[in] boxf Final box of transition.
Returns
Number of trajectories inside domain.
Record transitions
Add transition triplet, summing if duplicate
Convert to reduced indices
Add triplet in reduced indices
Add initial and final boxes to initial and final distributions,
respectively (not on a reduced grid).
Definition at line 735 of file transferOperator.cpp.
References finalDist, initDist, and mask.
Referenced by getTransitionCountTriplet(), and setMask().
allocateDist()
int transferOperator::allocateDist ()
Allocate memory for the distributions.
Returns
Exit status.
If stationary problem, initDist = finalDist = stationary distribution and the backward transition matrix need not be calculated
Definition at line 156 of file transferOperator.cpp.
References buildFromTransitionCount(), finalDist, getTransitionCountTriplet(), initDist, and nTraj.
Referenced by transferOperator().
buildFromTransitionCount()
void transferOperator::buildFromTransitionCount (const gsl_spmatrix * T, const size_t nTraj)
Buid transition matrices of transfer operator from transition count matrix.
Parameters
[in] T Transition count matrix.
[in] nTraj Number of trajectories (to define the minimum tolerance).
Convert to CRS summing duplicates
If the problem is not stationary, get final distribution and backward transition matrix
Get transpose copy
Make the backward transition matrix left stochastic
Make the forward transition matrix left stochastic
Definition at line 213 of file transferOperator.cpp.
References finalDist, gsl_spmatrix_div_cols(), gsl_vector_normalize(), initDist, nTraj, P, and Q.
Referenced by allocateDist(), and setMask().
filter()
int transferOperator::filter (double tol)
Filter weak Markov states (boxes) of forward and backward transition matrices based on their distributions.
Parameters
[in] tol Weight under which a state is filtered out.
Returns
Exit status.
Filter forward transition matrix
Filter forward transition matrix
Definition at line 264 of file transferOperator.cpp.
References filterStochasticMatrix(), finalDist, initDist, P, and Q.
Referenced by setMask().
getTransitionCountTriplet()
size_t transferOperator::getTransitionCountTriplet (const gsl_matrix_uint * gridMem, gsl_spmatrix * T)
Get the triplet vector counting the transitions from pairs of grid boxes from the grid membership matrix.
Parameters
[in] gridMem Grid membership matrix.
[out] T Triplet matrix counting the transitions.
Returns
Number of trajectories inside domain.
Initialize distributions to zero
Record transitions
Get initial and final boxes
Add transition triplet, summing if duplicate
Definition at line 777 of file transferOperator.cpp.
References addTransition(), finalDist, initDist, and nTraj.
Referenced by allocateDist(), and setMask().
printBackwardTransition()
int transferOperator::printBackwardTransition (const char * path, const char * fileFormat = "txt", const char * dataFormat = "%lf")
Print backward transition matrix to file in coordinate format with header (see transferOperator.hpp)
Parameters
[in] path Path to the file in which to print.
[in] fileFormat String "bin" or "txt" for the output type.
[in] dataFormat Format in which to print each element (if formatted output).
Returns
Status.
Definition at line 340 of file transferOperator.cpp.
References fileFormat, and Q.
Referenced by isStationary(), and main().
printFinalDist()
int transferOperator::printFinalDist (const char * path, const char * fileFormat = "txt", const char * dataFormat = "%lf")
Print final distribution to file.
Parameters
[in] path Path to the file in which to print.
[in] fileFormat String "bin" or "txt" for the output type.
[in] dataFormat Format in which to print each element (if formatted output).
Returns
Status.
Definition at line 421 of file transferOperator.cpp.
References fileFormat, and finalDist.
Referenced by isStationary(), and main().
printForwardTransition()
int transferOperator::printForwardTransition (const char * path, const char * fileFormat = "txt", const char * dataFormat = "%lf")
Print forward transition matrix to file in coordinate format with header (see transferOperator.hpp)
Parameters
[in] path Path to the file in which to print.
[in] fileFormat String "bin" or "txt" for the output type.
[in] dataFormat Format in which to print each element (if formatted output).
Returns
Status.
Definition at line 300 of file transferOperator.cpp.
References fileFormat, and P.
Referenced by isStationary(), and main().
printInitDist()
int transferOperator::printInitDist (const char * path, const char * fileFormat = "txt", const char * dataFormat = "%lf")
Print initial distribution to file.
Parameters
[in] path Path to the file in which to print.
[in] fileFormat String "bin" or "txt" for the output type.
[in] dataFormat Format in which to print each element (if formatted output).
Returns
Status.
Definition at line 388 of file transferOperator.cpp.
References fileFormat, and initDist.
Referenced by isStationary(), and main().
printMask()
int transferOperator::printMask (const char * path, const char * fileFormat = "txt", const char * dataFormat = "%lf")
Print mask to file.
Parameters
[in] path Path to the file in which to print.
[in] fileFormat String "bin" or "txt" for the output type.
[in] dataFormat Format in which to print each element (if formatted output).
Returns
Status.
Definition at line 454 of file transferOperator.cpp.
References fileFormat, and mask.
Referenced by isStationary().
scanBackwardTransition()
int transferOperator::scanBackwardTransition (const char * path, const char * fileFormat = "txt")
Scan backward transition matrix from file in coordinate format with header. (see transferOperator.hpp). No preliminary memory allocation needed but the grid size should be set. Previously allocated memory should first be freed to avoid memory leak.
Parameters
[in] path Path to the file in which to scan.
[in] fileFormat String "bin" or "txt" for the output type.
Returns
0 in success, EXIT_FAILURE otherwise.
Open file
Scan, summing if duplicate
Allocate before to read in CRS binary format
Read in Matrix Market format
Compress
Free
Check if transition matrix has been properly read
Set number of filled boxes in case not known already
Close
Definition at line 553 of file transferOperator.cpp.
References fileFormat, gsl_spmatrix_alloc2read(), and Q.
Referenced by isStationary(), and main().
scanFinalDist()
int transferOperator::scanFinalDist (const char * path, const char * fileFormat = "txt")
Scan final distribution from file. No preliminary memory allocation needed but the grid size should be set. Previously allocated memory should first be freed to avoid memory leak.
Parameters
[in] path Path to the file in which to scan.
[in] fileFormat String "bin" or "txt" for the output type.
Returns
0 in success, EXIT_FAILURE otherwise.
Scan after preallocating
Definition at line 660 of file transferOperator.cpp.
References fileFormat, and finalDist.
Referenced by isStationary(), and main().
scanForwardTransition()
int transferOperator::scanForwardTransition (const char * path, const char * fileFormat = "txt")
Scan forward transition matrix from file in coordinate format with header. (see transferOperator.hpp). No preliminary memory allocation needed but the grid size should be set. Previously allocated memory should first be freed to avoid memory leak.
Parameters
[in] path Path to the file in which to scan.
[in] fileFormat String "bin" or "txt" for the output type.
Returns
0 in success, EXIT_FAILURE otherwise.
Open file
Scan, summing if duplicate
Allocate before to read in CRS binary format
Read in Matrix Market format
Compress
Free
Check if transition matrix has been properly read
Set number of filled boxes in case not known already
Close
Definition at line 489 of file transferOperator.cpp.
References fileFormat, gsl_spmatrix_alloc2read(), and P.
Referenced by isStationary(), and main().
scanInitDist()
int transferOperator::scanInitDist (const char * path, const char * fileFormat = "txt")
Scan initial distribution from file. No preliminary memory allocation needed but the grid size should be set. Previously allocated memory should first be freed to avoid memory leak.
Parameters
[in] path Path to the file in which to scan.
[in] fileFormat String "bin" or "txt" for the output type.
Returns
0 in success, EXIT_FAILURE otherwise.
Scan after preallocating
Definition at line 626 of file transferOperator.cpp.
References fileFormat, and initDist.
Referenced by isStationary(), and main().
scanMask()
int transferOperator::scanMask (const char * path, const char * fileFormat = "txt")
Scan mask from file. No preliminary memory allocation needed but the grid size should be set. Previously allocated memory should first be freed to avoid memory leak.
Parameters
[in] path Path to the file in which to scan.
[in] fileFormat String "bin" or "txt" for the output type.
Returns
0 in success, EXIT_FAILURE otherwise.
Scan after preallocating
Definition at line 702 of file transferOperator.cpp.
References fileFormat, and mask.
Referenced by isStationary().
The documentation for this class was generated from the following files:
include/transferOperator.hpp
src/transferOperator.cpp