ergoPack: PolarGrid Class Reference
PolarGrid Class Reference
Polar grid.
#include <ergoGrid.hpp>
Public Member Functions
PolarGrid (const size_t nLevels, const size_t nSectors, const Grid *support, const gsl_matrix *states)
Construct a polar grid adapted to the time series.
~PolarGrid ()
Destructor desallocating memory.
int printGrid (const char *path, const char *dataFormat, const bool verbose) const
Print the grid to file.
Public Member Functions inherited from Grid
Grid (const gsl_vector_uint *nx_)
Constructor allocating an empty grid.
Grid (const size_t dim_, const size_t inx)
Constructor allocating an empty grid with same dimensions.
virtual ~Grid ()
Destructor.
size_t getDim () const
Get state space dimension.
size_t getN () const
Get number of grid boxes.
virtual size_t getBoxMembership (const gsl_vector *state) const =0
Get membership of a state to a box.
virtual void getBoxPosition (const size_t index, gsl_vector *position) const =0
Get center of position of grid box.
Additional Inherited Members
Protected Attributes inherited from Grid
const size_t dim
Number of dimensions.
const size_t N
Number of grid boxes.
Detailed Description
Definition at line 155 of file ergoGrid.hpp.
Constructor & Destructor Documentation
PolarGrid::PolarGrid (const size_t nLevels_, const size_t nSectors_, const Grid * support, const gsl_matrix * states)
Construct a polar grid adapted to the time series (yet, only for 2D).
Parameters
[in] nLevels_ Number of levels for the grid
[in] nSectors_ Number of sectors for the grid
[in] support Rectangular grid used to calculate the density.
[in] states Trajectory to which to adapt the grid.
The state is outside the support grid, mark it outside the polar grid
Definition at line 321 of file ergoGrid.hpp.
References Grid::dim, getDensityMLE(), getGridMemVector(), Grid::getN(), gsl_matrix_get_mean(), gsl_matrix_get_std(), Grid::N, nSTDHigh, nSTDLow, and nx.
PolarGrid::~PolarGrid ()
Destructor desallocating memory.
Definition at line 581 of file ergoGrid.hpp.
References A, Grid::dim, Grid::getBoxPosition(), getEOF(), Grid::getN(), and gsl_vector_max_index_among().
The documentation for this class was generated from the following file:
include/ergoGrid.hpp