ergoPack: periodicOrbitCont Class Reference
periodicOrbitCont Class Reference
Continuation
Continuation of periodic orbits.
#include <ODECont.hpp>
Public Member Functions
periodicOrbitCont (fundamentalMatrixModel *linMod_, const double epsDist_, const double epsStepCorrSize_, const size_t maxIter_, const double intStepCorr_, const size_t numShoot_=1, const bool verbose_=false)
Constructor assigning a linearized model and parameters.
void getExtendedState (gsl_vector *state, const size_t s)
Get extended state vector x(s), lambda.
void getCurrentState (gsl_vector *current_)
Get current state of tracking.
void setCurrentState (const size_t s)
Set current state from the current one.
void setCurrentState ()
Set current state from the current one.
void setCurrentState (const gsl_vector *init)
Set current state.
void getInitialState (gsl_vector *initial_)
Get initial state of tracking.
void setInitialState (const size_t s)
Set initial state from the initial one.
void setInitialState (const gsl_vector *init)
Set initial state.
void correct (const gsl_vector *init)
Correction of initial state.
void correct ()
Correction after prediction.
void updateTargetCorr ()
Update correction target vector for periodic orbit tracking.
void continueStep (const double contStep, const gsl_vector *init)
Perform one step (correct. + predict.) of peudo-arc. cont.
void continueStep (const double contStep)
Perform one step (correct. + predict.) of peudo-arc. cont.
void getSystemCorr ()
Get matrix of the linear system to be solved for correction.
void getSystemPred ()
Get matrix of the linear system to be solved for prediction.
Public Member Functions inherited from periodicOrbitTrack
periodicOrbitTrack (fundamentalMatrixModel *linMod_, const double epsDist_, const double epsStepCorrSize_, const size_t maxIter_, const double intStepCorr_, const size_t numShoot_=1, const bool verbose_=false)
Constructor assigning a linearized model and parameters.
size_t getNumShoot ()
Get number of shoots.
void initialize ()
Initialize.
void getStabilityMatrix (gsl_matrix *matrix)
Get the fundamental matrix of the solution.
Public Member Functions inherited from solutionCorrection
solutionCorrection (const double epsDist_, const double epsStepCorrSize_, const size_t maxIter_, const bool verbose_=false)
Constructor assigning a linearized model and parameters.
size_t getDim ()
Return the dimension of the problem.
size_t getNumIter ()
Return the number of iterations used for tracking.
double getDist ()
Return the last distance to the targetCorr.
double getStepCorrSize ()
Return the size of the last stepCorr.
bool hasConverged ()
Return the flag for the convergence of the tracking.
void NewtonStep ()
Perform a Newton step to find a fixed point.
void applyCorr (const double damping=1)
Correct with the stepCorr obtained from the Newton stepCorr.
virtual ~solutionCorrection ()
Destructor.
void setInitialStateToCurrent ()
Set initial state to current state.
Public Member Functions inherited from solutionCont
solutionCont (const size_t verboseCont_)
Constructor.
~solutionCont ()
Default destructor.
void applyPredict (const double contStep, gsl_vector *current)
Update state after prediction.
void predict (gsl_matrix *S)
Prediction Newton-Raphson step.
Additional Inherited Members
Public Attributes inherited from periodicOrbitTrack
fundamentalMatrixModel *const linMod
Full and linearized model.
Protected Member Functions inherited from periodicOrbitTrack
virtual void adaptTimeToPeriod (const double T)
Adapt time step and number of time steps for a give period.
Protected Attributes inherited from periodicOrbitTrack
const double intStepCorr
Int. time stepCorr (to be adap. to period).
size_t nt
Total number of integration step.
gsl_vector_uint * ntShoot
Number of integration step per shoot.
double dt
Adapted time step.
const size_t numShoot
Number of shoots to correct/predict orbit.
Protected Attributes inherited from solutionCorrection
size_t dim
Dimension of the problem.
const double epsDist
Tolerance in the distance to zero.
const double epsStepCorrSize
Tolerance in the size of stepCorr.
const size_t maxIter
Maximum number of iterations.
double errDist
Distance to zero.
double errStepCorrSize
Size of stepCorr.
gsl_vector * stepCorr
StepCorr correcting the solution.
gsl_vector * targetCorr
TargetCorr vector.
size_t numIter
Number of iterations.
bool converged
Flag for convergence of the tracking.
gsl_matrix * S
Matrix of linear system to solve (workspace).
gsl_vector * current
Current state of tracking.
gsl_vector * initial
Initial state of tracking.
bool verbose
Verbose mode.
Protected Attributes inherited from solutionCont
gsl_vector * stepPred
Step of prediction.
gsl_vector * targetPred
(0, ..., 0, 1) vector for prediction
const bool verboseCont
Verbose mode.
Detailed Description
Continuation of periodic orbits.
Definition at line 390 of file ODECont.hpp.
Member Function Documentation
continueStep() [1/2]
void periodicOrbitCont::continueStep (const double contStep, const gsl_vector * init)
Perform one step (correction + prediction) of pseudo-arclength continuation from initial state.
Parameters
[in] contStep Continuation step size.
[in] init Vector from which to start tracking.
Definition at line 1419 of file ODECont.cpp.
References solutionCorrection::setInitialState().
continueStep() [2/2]
void periodicOrbitCont::continueStep (const double contStep)
Perform one step (correction + prediction) of pseudo-arclength continuation from current step.
Parameters
[in] contStep Continuation step size.
Definition at line 1437 of file ODECont.cpp.
References contStep, solutionCorrection::converged, solutionCorrection::current, solutionCorrection::dim, solutionCorrection::numIter, numShoot, solutionCorrection::S, solutionCorrection::setCurrentState(), and solutionCorrection::verbose.
correct() [1/2]
void periodicOrbitCont::correct (const gsl_vector * init)
Correct initial state.
Definition at line 1310 of file ODECont.cpp.
References solutionCorrection::setInitialState().
correct() [2/2]
void periodicOrbitCont::correct ()
Correct prediction by pseudo-arclenght continuation and Newton-Raphson.
Update state of model and Jacobian to current state and reinitizlize fundamental matrix to identity (after integration in updateTargetCorr).
Update state of model and Jacobian to current state and reinitizlize fundamental matrix to identity.
Update the convergence flag.
Definition at line 1326 of file ODECont.cpp.
References solutionCorrection::applyCorr(), solutionCorrection::converged, solutionCorrection::current, solutionCorrection::dim, solutionCorrection::epsDist, solutionCorrection::epsStepCorrSize, solutionCorrection::errDist, solutionCorrection::errStepCorrSize, gsl_vector_get_norm(), solutionCorrection::maxIter, solutionCorrection::NewtonStep(), solutionCorrection::numIter, numShoot, solutionCorrection::setCurrentState(), solutionCorrection::stepCorr, solutionCorrection::targetCorr, solutionCorrection::updateTargetCorr(), and solutionCorrection::verbose.
getCurrentState()
void periodicOrbitCont::getCurrentState (gsl_vector * current_) virtual
Get current state of tracking. If current_->size == dim + 1, return x(0), T else if current_->size == dim*numShoot + 1, return x(0), ..., x(numShoot-1), T
Parameters
[in] current_ Vector in which to copy the current state.
Reimplemented from periodicOrbitTrack.
Definition at line 986 of file ODECont.cpp.
References solutionCorrection::current, solutionCorrection::dim, and numShoot.
Referenced by getFloquet(), and normalizeFloquet().
getExtendedState()
void periodicOrbitCont::getExtendedState (gsl_vector * state, const size_t s)
Get extended state vector .
Parameters
[out] state Vector in which to copy the extended state.
[in] s Shooting number.
Definition at line 966 of file ODECont.cpp.
References solutionCorrection::current, solutionCorrection::dim, and numShoot.
getInitialState()
void periodicOrbitCont::getInitialState (gsl_vector * initial_) virtual
Get initial state of tracking. If initial_->size == dim + 1, return x(0), T else if initial_->size == dim*numShoot + 1, return x(0), ..., x(numShoot-1), T
Parameters
[in] initial_ Vector in which to copy the initial state.
Reimplemented from periodicOrbitTrack.
Definition at line 1108 of file ODECont.cpp.
References solutionCorrection::dim, solutionCorrection::initial, and numShoot.
getSystemCorr()
void periodicOrbitCont::getSystemCorr () virtual
Get matrix of the linear system to be solved for correction.
Implements periodicOrbitTrack.
Definition at line 1194 of file ODECont.cpp.
References solutionCorrection::dim, dt, numShoot, solutionCorrection::S, and solutionCorrection::setCurrentState().
getSystemPred()
void periodicOrbitCont::getSystemPred () virtual
Get matrix of the linear system to be solved for prediction.
Implements solutionCont.
Definition at line 1298 of file ODECont.cpp.
References solutionCorrection::getSystemCorr().
setCurrentState() [1/3]
void periodicOrbitCont::setCurrentState (const size_t s)
Set current state , lambda of the model and fundamental matrix
Parameters
[in] s Shooting number
Definition at line 1020 of file ODECont.cpp.
References solutionCorrection::verbose.
setCurrentState() [2/3]
void periodicOrbitCont::setCurrentState () virtual
Set current state , lambda of the model and fundamental matrix
Reimplemented from periodicOrbitTrack.
Definition at line 1038 of file ODECont.cpp.
References solutionCorrection::setCurrentState().
setCurrentState() [3/3]
void periodicOrbitCont::setCurrentState (const gsl_vector * init) virtual
Set current state of the problem together with that of the model.
Parameters
[in] init Initial state.
Only has been given, integrate to and set
Reimplemented from periodicOrbitTrack.
Definition at line 1052 of file ODECont.cpp.
References solutionCorrection::current, solutionCorrection::dim, dt, numShoot, and solutionCorrection::setCurrentState().
setInitialState()
void periodicOrbitCont::setInitialState (const gsl_vector * init) virtual
Set initial state of the problem together with that of the model.
Parameters
[in] init Initial state.
Reimplemented from periodicOrbitTrack.
Definition at line 1141 of file ODECont.cpp.
References solutionCorrection::current, solutionCorrection::dim, dt, solutionCorrection::initial, solutionCorrection::initialize(), and numShoot.
updateTargetCorr()
void periodicOrbitCont::updateTargetCorr () virtual
Update correction target vector for fixed point tracking.
Integrate model for a period from the new current state after initializing the linear model to x(s) (no need to update the linear model here).
Implements periodicOrbitTrack.
Definition at line 1256 of file ODECont.cpp.
References solutionCorrection::dim, dt, numShoot, solutionCorrection::setCurrentState(), solutionCorrection::targetCorr, and solutionCorrection::verbose.
The documentation for this class was generated from the following files:
include/ODECont.hpp
src/ODECont.cpp