ergoPack: saddleNodeField Class Reference
saddleNodeField Class Reference
Simulating
Vector field for the normal form of the saddle-node bifurcation.
#include <ODEFields.hpp>
Public Member Functions
saddleNodeField (const param *p_)
Constructor defining the model parameters.
void evalField (const gsl_vector *state, gsl_vector *field)
Evaluate the saddle-node vector field at a given state.
Public Member Functions inherited from vectorField
vectorField ()
Default onstructor.
vectorField (const param *p_)
Constructor.
virtual ~vectorField ()
Destructor.
virtual void getParameters (param *p_)
Return the parameters of the model.
virtual void setParameters (const param *p_)
Set parameters of the model.
Additional Inherited Members
Protected Attributes inherited from vectorField
param p
Parameters.
Detailed Description
Vector field for the normal form of the saddle-node bifurcation (Guckenheimer and Holmes, 1988, Strogatz 1994):
      F(x) = \mu - x^2.
Definition at line 32 of file ODEFields.hpp.
Member Function Documentation
evalField()
void saddleNodeField::evalField (const gsl_vector * state, gsl_vector * field) virtual
Evaluate the vector field of the normal form of the saddleNode bifurcation (Guckenheimer & Holmes, 1988, Strogatz, 1994) at a given state:
    F(x) = \mu - x^2
Parameters
[in] state State at which to evaluate the vector field.
[out] field Vector resulting from the evaluation of the vector field.
Implements vectorField.
Definition at line 29 of file ODEFields.cpp.
References vectorField::p.
Referenced by pitchforkField::pitchforkField(), pitchforkSubField::pitchforkSubField(), saddleNodeField(), transcriticalField::transcriticalField(), cuspField::~cuspField(), Hopf::~Hopf(), HopfCont::~HopfCont(), Lorenz63::~Lorenz63(), and Lorenz63Cont::~Lorenz63Cont().
The documentation for this class was generated from the following files:
include/ODEFields.hpp
src/ODEFields.cpp