ergoPack: solutionCorrection Class Reference
solutionCorrection Class Reference abstract
Abstract class for Newton corrections.
#include <ODECont.hpp>
Public Member Functions
solutionCorrection (const double epsDist_, const double epsStepCorrSize_, const size_t maxIter_, const bool verbose_=false)
Constructor assigning a linearized model and parameters.
size_t getDim ()
Return the dimension of the problem.
size_t getNumIter ()
Return the number of iterations used for tracking.
double getDist ()
Return the last distance to the targetCorr.
double getStepCorrSize ()
Return the size of the last stepCorr.
bool hasConverged ()
Return the flag for the convergence of the tracking.
void NewtonStep ()
Perform a Newton step to find a fixed point.
void applyCorr (const double damping=1)
Correct with the stepCorr obtained from the Newton stepCorr.
virtual ~solutionCorrection ()
Destructor.
virtual void getCurrentState (gsl_vector *current_)
Get current state of tracking.
virtual void setCurrentState ()=0
Set current state.
virtual void setCurrentState (const gsl_vector *init)=0
Set current state.
virtual void getInitialState (gsl_vector *initial_)
Get initial state of tracking.
virtual void setInitialState (const gsl_vector *init)=0
Set initial state.
virtual void initialize ()=0
Initialize.
void setInitialStateToCurrent ()
Set initial state to current state.
virtual void updateTargetCorr ()=0
Update targetCorr.
virtual void getStabilityMatrix (gsl_matrix *matrix)=0
Get stability matrix associated with the solution.
virtual void getSystemCorr ()=0
Get matrix of the linear system to be solved for correction.
Protected Attributes
size_t dim
Dimension of the problem.
const double epsDist
Tolerance in the distance to zero.
const double epsStepCorrSize
Tolerance in the size of stepCorr.
const size_t maxIter
Maximum number of iterations.
double errDist
Distance to zero.
double errStepCorrSize
Size of stepCorr.
gsl_vector * stepCorr
StepCorr correcting the solution.
gsl_vector * targetCorr
TargetCorr vector.
size_t numIter
Number of iterations.
bool converged
Flag for convergence of the tracking.
gsl_matrix * S
Matrix of linear system to solve (workspace).
gsl_vector * current
Current state of tracking.
gsl_vector * initial
Initial state of tracking.
bool verbose
Verbose mode.
Detailed Description
Abstract class for Newton correction of zeros.
Definition at line 29 of file ODECont.hpp.
Member Function Documentation
applyCorr()
void solutionCorrection::applyCorr (const double damping = 1)
Update state after Newton step.
Parameters
[in] damping Damping to apply to the Newton step.
Definition at line 57 of file ODECont.cpp.
References current, stepCorr, and verbose.
Referenced by fixedPointCont::correct(), periodicOrbitCont::correct(), fixedPointCorr::findSolution(), periodicOrbitCorr::findSolution(), and hasConverged().
getCurrentState()
void solutionCorrection::getCurrentState (gsl_vector * current_) virtual
Get current state of tracking.
Parameters
[in] current_ Vector in which to copy the current state.
Reimplemented in periodicOrbitCont, and periodicOrbitTrack.
Definition at line 33 of file ODECont.cpp.
References current.
Referenced by periodicOrbitTrack::getNumShoot(), periodicOrbitCont::periodicOrbitCont(), and ~solutionCorrection().
getInitialState()
void solutionCorrection::getInitialState (gsl_vector * initial_) virtual
Get initial state of tracking.
Parameters
[in] initial_ Vector in which to copy the initial state.
Reimplemented in periodicOrbitCont, and periodicOrbitTrack.
Definition at line 45 of file ODECont.cpp.
References initial.
Referenced by periodicOrbitTrack::getNumShoot(), periodicOrbitCont::periodicOrbitCont(), and ~solutionCorrection().
NewtonStep()
void solutionCorrection::NewtonStep ()
Perform a Newton step to find a fixed point.
Definition at line 76 of file ODECont.cpp.
References getSystemCorr(), p, S, stepCorr, targetCorr, and verbose.
Referenced by fixedPointCont::correct(), periodicOrbitCont::correct(), fixedPointCorr::findSolution(), periodicOrbitCorr::findSolution(), and hasConverged().
The documentation for this class was generated from the following files:
include/ODECont.hpp
src/ODECont.cpp