ergoPack: modelSDDE Class Reference
modelSDDE Class Reference
Simulation
Numerical SDDE model class.
#include <SDDESolvers.hpp>
Public Member Functions
modelSDDE (vectorFieldDelay *delayedField_, vectorFieldStochastic *stocField_, numericalSchemeSDDE *scheme_)
Constructor assigning a delayed vector field, a numerical scheme and a stochastic vector field and setting initial historic constant to origin.
modelSDDE (vectorFieldDelay *delayedField_, vectorFieldStochastic *stocField_, numericalSchemeSDDE *scheme_, gsl_vector *initStateCst)
Constructor assigning a delayed vector field, a numerical scheme and a stochastic vector field and setting a constant initial state.
modelSDDE (vectorFieldDelay *delayedField_, vectorFieldStochastic *stocField_, numericalSchemeSDDE *scheme_, gsl_matrix *initState)
Constructor assigning a delayed vector field, a numerical scheme and a stochastic vector field and setting the initial state.
~modelSDDE ()
Destructor freeing memory.
void stepForward ()
One time-step forward integration of the modelSDDE.
gsl_matrix * integrateForward (const double length, const double spinup, const size_t sampling)
Integrate the modelSDDE forward for a given period.
Protected Attributes
const size_t dim
Phase space dimension.
const size_t nDelays
Number of delays.
const size_t delayMax
Maximum delay in number of time steps.
vectorFieldDelay * delayedField
Vector field for each delay.
vectorFieldStochastic * stocField
Stochastic vector field.
numericalSchemeSDDE * scheme
Numerical scheme.
gsl_matrix * currentState
Current state (historic)
Detailed Description
Numerical SDDE model class. An SDDE model is defined by a delayed vector field, a stochastic vector field and a numerical scheme. The current state (a historic of present and past states) of the model is also recorded. Attention: the constructors do not copy the delayed vector field and the numerical scheme given to them, so that any modification or freeing will affect the model.
Definition at line 146 of file SDDESolvers.hpp.
Member Function Documentation
gsl_matrix * modelSDDE::integrateForward (const double length, const double spinup, const size_t sampling)
Integrate the SDDE model forward for a given period.
Parameters
[in] length Duration of the integration.
[in] spinup Initial integration period to remove.
[in] sampling Time step at which to save states.
Returns
Matrix to record the states.
Definition at line 177 of file SDDESolvers.cpp.
References currentState, dim, numericalSchemeSDDE::getTimeStep(), nt, scheme, and stepForward().
Referenced by main().
void modelSDDE::stepForward ()
Integrate one step forward the SDDE model with the numerical scheme.
Definition at line 160 of file SDDESolvers.cpp.
References currentState, delayedField, scheme, numericalSchemeSDDE::stepForward(), and stocField.
Referenced by integrateForward().
The documentation for this class was generated from the following files:
include/SDDESolvers.hpp
src/SDDESolvers.cpp