ergoPack: include/ergoGrid.hpp File Reference
ergoGrid.hpp File Reference
Various grid definitions used for Galerkin approximation.
#include <iostream>
#include <vector>
#include <stdexcept>
#include <ios>
#include <cmath>
#include <gsl/gsl_math.h>
#include <gsl/gsl_vector.h>
#include <gsl/gsl_matrix.h>
#include <ergoPack/gsl_extension.h>
#include <ergoPack/ergoStat.hpp>
Classes
class Grid
Grid class.
class CurvilinearGrid
Curvilinear Grid.
class RegularGrid
Regular grid.
class PolarGrid
Polar grid.
Functions
gsl_matrix_uint * getGridMemMatrix (const gsl_matrix *initStates, const gsl_matrix *finalStates, const Grid *grid)
Get membership matrix from initial and final states for a grid.
gsl_matrix_uint * getGridMemMatrix (const gsl_matrix *states, const Grid *grid, const size_t tauStep)
Get the grid membership vector from a single long trajectory.
gsl_vector_uint * getGridMemVector (const gsl_matrix *states, const Grid *grid)
Get the grid membership matrix from a single long trajectory.
gsl_matrix_uint * memVector2memMatrix (const gsl_vector_uint *gridMemVect, size_t tauStep)
Get the grid membership matrix from the membership vector for a given lag.
gsl_matrix_uint * memVectorList2memMatrix (const std::vector< gsl_vector_uint * > *memList, size_t tauStep)
Concatenate a list of membership vectors into one membership matrix.
void getDensityMLE (const gsl_vector_uint *gridMemVect, const Grid *grid, gsl_vector *density)
Get MLE of a density from the grid membership vector of a time series.
gsl_matrix_uint * memVector2memMatrix (gsl_vector_uint *gridMemVect, size_t tauStep)
Detailed Description
Various grid definitions used for Galerkin approximation.
Definition in file ergoGrid.hpp.
Function Documentation
void getDensityMLE (const gsl_vector_uint * gridMemVect, const Grid * grid, gsl_vector * density)
Get Maximum Likelihood Estimator of a density from the membership vector of a time series to a grid.
Parameters
[in] gridMemVect Grid membership vector.
[in] grid Grid.
[out] density MLE of the density on the grid.
Definition at line 914 of file ergoGrid.hpp.
References Grid::getN(), Grid::N, and nt.
Referenced by PolarGrid::PolarGrid(), and PolarGrid::printGrid().
gsl_matrix_uint * getGridMemMatrix (const gsl_matrix * initStates, const gsl_matrix * finalStates, const Grid * grid)
Get membership matrix from initial and final states for a grid.
Parameters
[in] initStates GSL matrix of initial states.
[in] finalStates GSL matrix of final states.
[in] grid Pointer to Grid object.
Returns
GSL grid membership matrix.
Definition at line 743 of file ergoGrid.hpp.
References Grid::dim, Grid::getBoxMembership(), and Grid::getN().
Referenced by PolarGrid::printGrid(), and transferOperator::transferOperator().
gsl_matrix_uint * getGridMemMatrix (const gsl_matrix * states, const Grid * grid, const size_t tauStep)
Get the grid membership matrix from a single long trajectory.
Parameters
[in] states GSL matrix of states for each time step.
[in] grid Pointer to Grid object.
[in] tauStep Lag used to calculate the transitions.
Returns
GSL grid membership matrix.
Definition at line 854 of file ergoGrid.hpp.
References getGridMemVector(), and memVector2memMatrix().
gsl_vector_uint * getGridMemVector (const gsl_matrix * states, const Grid * grid)
Get the grid membership vector from a single long trajectory.
Parameters
[in] states GSL matrix of states for each time step.
[in] grid Pointer to Grid object.
Returns
GSL grid membership vector.
Definition at line 791 of file ergoGrid.hpp.
References Grid::dim, and Grid::getBoxMembership().
Referenced by getGridMemMatrix(), main(), PolarGrid::PolarGrid(), and PolarGrid::printGrid().
gsl_matrix_uint* memVector2memMatrix (gsl_vector_uint * gridMemVect, size_t tauStep)
Get the grid membership matrix from the membership vector for a given lag.
Parameters
[in] gridMemVect Grid membership vector of a long trajectory for a grid.
[in] tauStep Lag used to calculate the transitions.
Returns
GSL grid membership matrix.
Definition at line 830 of file ergoGrid.hpp.
gsl_matrix_uint * memVectorList2memMatrix (const std::vector< gsl_vector_uint * > * memList, size_t tauStep)
Concatenate a list of membership vectors into one membership matrix.
Parameters
[in] memList STD vector of membership Vectors each of them associated with a single long trajectory.
[in] tauStep Lag used to calculate the transitions.
Returns
GSL grid membership matrix.
Definition at line 876 of file ergoGrid.hpp.
References memVector2memMatrix().
Referenced by PolarGrid::printGrid().