ergoPack: Transfer operators
Transfer operators
Files
file transferOperator.hpp
Calculate discretized approximation of transfer/Koopman operators from time series.
file transferSpectrum.hpp
Get spectrum of transferOperator using ARPACK++.
Classes
class transferOperator
Transfer operator class.
struct configAR
Utility structure used to give configuration options to ARPACK++.
class gsl_spmatrix2AR
Interface from GSL sparse matrices to ARPACK++.
class transferSpectrum
Transfer operator spectrum.
Functions
void getTransitionCountTriplet (const gsl_matrix_uint *gridMem, size_t N, gsl_spmatrix *T, gsl_vector *initDist, gsl_vector *finalDist)
Get triplet vector from membership matrix.
int filterStochasticMatrix (gsl_spmatrix *M, gsl_vector *rowCut, gsl_vector *colCut, double tol, int norm)
Remove weak nodes from a transition matrix.
void getSpectrumAR (const int nev, ARNonSymStdEig< double, gsl_spmatrix2AR > *EigProb, gsl_spmatrix2AR *gsl2AR, configAR cfgAR, gsl_vector_complex *EigVal, gsl_matrix_complex *EigVec)
Get spectrum of a nonsymmetric matrix using ARPACK++.
void writeSpectrumAR (FILE *fEigVal, FILE *fEigVec, const gsl_vector_complex *EigVal, const gsl_matrix_complex *EigVec)
Write spectrum of a nonsymmetric matrix using ARPACK++.
transferOperator::transferOperator (const gsl_matrix_uint *gridMem, const size_t N_, const bool stationary_)
Constructor from the membership matrix.
transferOperator::transferOperator (const gsl_matrix *initStates, const gsl_matrix *finalStates, const Grid *grid, const bool stationary_)
Constructor from initial and final states for a given grid.
transferOperator::transferOperator (const gsl_matrix *states, const Grid *grid, size_t tauStep)
Constructor from a long trajectory for a given grid and lag.
transferOperator::~transferOperator ()
Destructor.
int transferOperator::filter (double tol)
Filtering of weak Markov states.
int transferOperator::printForwardTransition (const char *path, const char *dataFormat)
Print forward transition matrix to file in coordinate format.
int transferOperator::printBackwardTransition (const char *path, const char *dataFormat)
Print backward transition matrix to file in coordinate format.
int transferOperator::printInitDist (const char *path, const char *dataFormat)
Print initial distribution to file.
int transferOperator::printFinalDist (const char *path, const char *dataFormat)
Print final distribution to file.
int transferOperator::scanForwardTransition (const char *path)
Scan forward transition matrix to file in coordinate format.
int transferOperator::scanBackwardTransition (const char *path)
Scan backward transition matrix to file in coordinate format.
int transferOperator::scanInitDist (const char *path)
Scan initial distribution to file.
int transferOperator::scanFinalDist (const char *path)
Scan final distribution to file.
transferSpectrum::transferSpectrum (const int nev_, const transferOperator *transferOp_, const configAR cfgAR)
Constructor allocating for nev_ eigenvalues and vectors.
transferSpectrum::~transferSpectrum ()
Destructor desallocating.
void transferSpectrum::getSpectrumForward ()
Get spectrum of forward transition matrices.
void transferSpectrum::getSpectrumBackward ()
Get spectrum of backward transition matrices.
void transferSpectrum::getSpectrum ()
Get spectrum of both forward and backward transition matrices.
gsl_vector * transferSpectrum::getConditionNumbers ()
Get condition number associated with each eigenvalues.
gsl_vector_complex * transferSpectrum::getWeights (const gsl_vector *f, const gsl_vector *g)
Get weights for two observables.
void transferSpectrum::sort ()
Sort by largest magnitude.
void transferSpectrum::makeBiorthonormal ()
Make set of forward and backward eigenvectors biorthonormal.
void transferSpectrum::writeSpectrumForward (const char *EigValForwardFile, const char *EigVecForwardFile) const
Write forward eigenvalues and eigenvectors.
void transferSpectrum::writeSpectrumBackward (const char *EigValBackwardFile, const char *EigVecBackwardFile) const
Write backward eigenvalues and eigenvectors.
void transferSpectrum::writeSpectrum (const char *EigValForwardFile, const char *EigVecForwardFile, const char *EigValBackwardFile, const char *EigVecBackwardFile) const
Write forward and backward eigenvalues and eigenvectors.
virtual void gsl_spmatrix2AR::MultMv (double *v, double *w)
Matrix-vector product required by ARPACK.
Variables
configAR defaultCfgAR = {"LM", 0, 0., 0, NULL, true}
Detailed Description
Function Documentation
int transferOperator::filter (double tol)
#include <include/transferOperator.hpp>
Filter weak Markov states (boxes) of forward and backward transition matrices based on their distributions.
Parameters
[in] tol Weight under which a state is filtered out.
Returns
Exit status.
Filter forward transition matrix
Filter forward transition matrix
Definition at line 362 of file transferOperator.hpp.
References filterStochasticMatrix(), transferOperator::finalDist, transferOperator::initDist, transferOperator::P, and transferOperator::Q.
Referenced by transferOperator::setFinalDist().
int filterStochasticMatrix (gsl_spmatrix * M, gsl_vector * rowCut, gsl_vector * colCut, double tol, int norm)
#include <include/transferOperator.hpp>
Set weak states to 0 from a stochastic matrix and its distributions based on initial and final probability of each Markov state. Attention: elements are not actually removed from sparse matrix.
Parameters
[in,out] M Compressed transition matrix to filter.
[in] rowCut The probability distribution associated with each row.
[in] colCut The probability distribution associated with each column.
[in] tol Probability under which Markov states are removed.
[in] norm Choice of normalization,
norm = 0: normalize over all elements,
norm = 1: to right stochastic,
norm = 2: to left stochastic,
no normalization for any other choice.
Check which nodes should be filtered and set distribution to 0
Make matrix and vectors stochastic again
Free
Definition at line 766 of file transferOperator.hpp.
References gsl_spmatrix_div_cols(), gsl_spmatrix_div_rows(), gsl_spmatrix_get_colsum(), gsl_spmatrix_get_rowsum(), gsl_spmatrix_get_sum(), and gsl_vector_normalize().
Referenced by transferOperator::filter(), and transferOperator::setFinalDist().
gsl_vector * transferSpectrum::getConditionNumbers ()
#include <include/transferSpectrum.hpp>
Get condition numbers associated with each eigenvalue. The condition number associated with eigenvalue is , where and are the forward and backward (adjoint) eigenvectors, respectively and norm is for w.r.t the initial or final distributions. The condition number is equal to the inverse of the cosine of the angle between the two vectors and gives a measure of the nonnormality associated with a particular pair of eigenvectors.
Returns
Condition numbers associated with each pair of eigenvectors.
Get norms of eigenvectors
Get norm of forward eigenvector
Get norm of backward eigenvector.
Divide by their inner product (in case not made biorthonormal)
Set condition number
Definition at line 340 of file transferSpectrum.hpp.
References transferSpectrum::EigVecBackward, transferSpectrum::EigVecForward, transferOperator::finalDist, gsl_vector_complex_get_inner_product(), gsl_vector_complex_get_norm(), and transferOperator::initDist.
void transferSpectrum::getSpectrum ()
#include <include/transferSpectrum.hpp>
Get spectrum of transfer operator, including the complex eigenvalues, the left eigenvectors of the forward transition matrix and the right eigenvectors of the backward transitioin matrix. The vectors of eigenvalues and eigenvectors should not be preallocated.
Get spectrum of forward transition matrix
Get spectrum of backward transition matrix
Definition at line 315 of file transferSpectrum.hpp.
References transferSpectrum::getSpectrumBackward(), and transferSpectrum::getSpectrumForward().
void getSpectrumAR (const int nev, ARNonSymStdEig< double, gsl_spmatrix2AR > * EigProb, gsl_spmatrix2AR * gsl2AR, configAR cfgAR, gsl_vector_complex * EigVal, gsl_matrix_complex * EigVec)
#include <include/transferSpectrum.hpp>
Get spectrum of a nonsymmetric matrix using ARPACK++.
Parameters
[in] nev Number of eigenvalues and eigenvectors to find.
[in,out] EigProb Eigen problem to use.
[in] gsl2AR Object interfacing the GSL sparse matrix to ARPACK++.
[in] cfgAR Configuration options passed as a configAR object.
[out] EigVal Found eigenvalues.
[out] EigVec Found eigenvectors.
Define non-hermitian eigenvalue problem
Find eigenvalues and left eigenvectors with ARPACK++
Save eigenvalues and eigenvectors and their complex conjugate
Definition at line 711 of file transferSpectrum.hpp.
References configAR::AutoShift, gsl_spmatrix2AR::M, configAR::maxit, gsl_spmatrix2AR::MultMv(), configAR::ncv, configAR::resid, configAR::tol, and configAR::which.
Referenced by transferSpectrum::getSpectrumBackward(), transferSpectrum::getSpectrumForward(), and transferSpectrum::setConfig().
void transferSpectrum::getSpectrumBackward ()
#include <include/transferSpectrum.hpp>
Get spectrum of backward transition matrix.
Get transpose of backward transition matrix in ARPACK CCS format
In the stationary case, the adjoint eigenvectors can be calculated as left eigenvectors of the forward transition matrix divided by the stationary distribution
Get eigenvalues and vectors of backward transition matrix
Divide eigenvectors (real and imaginary parts) by stationary distribution
Definition at line 254 of file transferSpectrum.hpp.
References transferSpectrum::EigProbBackward, transferSpectrum::EigValBackward, transferSpectrum::EigVecBackward, getSpectrumAR(), transferOperator::initDist, transferOperator::P, and transferOperator::Q.
Referenced by transferSpectrum::getSpectrum(), and main().
void transferSpectrum::getSpectrumForward ()
#include <include/transferSpectrum.hpp>
Get spectrum of forward transition matrix.
Get transpose of forward transition matrix in CCS Transposing is trivial since the transition matrix is in CRS format. However, it is more secure to avoid directly changing the type of the transition matrix.
Solve eigen value problem using user-defined ARPACK++
Definition at line 222 of file transferSpectrum.hpp.
References transferSpectrum::EigProbForward, transferSpectrum::EigValForward, transferSpectrum::EigVecForward, getSpectrumAR(), and transferOperator::P.
Referenced by transferSpectrum::getSpectrum(), and main().
void getTransitionCountTriplet (const gsl_matrix_uint * gridMem, size_t N, gsl_spmatrix * T, gsl_vector * initDist = NULL, gsl_vector * finalDist = NULL)
#include <include/transferOperator.hpp>
Get the triplet vector counting the transitions from pairs of grid boxes from the grid membership matrix.
Parameters
[in] gridMem Grid membership matrix.
[in] N Size of the grid.
[out] T Triplet matrix counting the transitions.
[out] initDist Initial states count
[out] finalDist Final states count
Record transitions
Add transition triplet, summing if duplicate
Definition at line 708 of file transferOperator.hpp.
References transferOperator::finalDist, and transferOperator::initDist.
Referenced by transferOperator::setFinalDist(), and transferOperator::~transferOperator().
gsl_vector_complex * transferSpectrum::getWeights (const gsl_vector * f, const gsl_vector * g)
#include <include/transferSpectrum.hpp>
Get weights associated with the projection of two observables on the backward and forward eigenvectors, respectively, i.e. .
Parameters
[in] f Vector representing the first observable, projected on the backward eigenvectors.
[in] g Vector representing the second observable, projected on the forward eigenvectors.
Returns
Weights associated with each pair of eigenvectors for the two observables.
Definition at line 382 of file transferSpectrum.hpp.
References transferSpectrum::EigVecBackward, transferSpectrum::EigVecForward, transferOperator::finalDist, gsl_vector_complex_get_inner_product(), gsl_vector_complex_memcpy_real(), and transferOperator::initDist.
void transferSpectrum::makeBiorthonormal ()
#include <include/transferSpectrum.hpp>
Make set of forward and backward eigenvectors biorthonormal.
Test that both forward and backward eigen problems have been solved and that eigenvalues and eigenvectors have been sorted.
Normalize backward eigenvectors by the scalar product with forward eigenvectors to make biorthonormal set.
Get inner product of forward and backward eigenvectors
Divide backward eigenvector by conjugate of inner product
Definition at line 503 of file transferSpectrum.hpp.
References transferSpectrum::EigValBackward, transferSpectrum::EigValForward, transferSpectrum::EigVecBackward, transferSpectrum::EigVecForward, transferOperator::finalDist, gsl_vector_complex_get_inner_product(), and transferSpectrum::sort().
Referenced by main().
void gsl_spmatrix2AR::MultMv (double * v, double * w) virtual
#include <include/transferSpectrum.hpp>
Matrix-vector product required by ARPACK++ when using user-defined matrices (GSL sparse matrices). Modified version of gsl_spblas_dgemv in gsl_spmatrix.h .
Parameters
[in] v Vector to multiply.
[out] w Vector storing the result of multiplication.
Definition at line 650 of file transferSpectrum.hpp.
Referenced by getSpectrumAR(), and gsl_spmatrix2AR::gsl_spmatrix2AR().
int transferOperator::printBackwardTransition (const char * path, const char * dataFormat = "%lf")
#include <include/transferOperator.hpp>
Print backward transition matrix to file in coordinate format with header (see transferOperator.hpp)
Parameters
[in] path Path to the file in which to print.
[in] dataFormat Format in which to print each element.
Returns
Status.
Definition at line 430 of file transferOperator.hpp.
References transferOperator::Q.
Referenced by transferOperator::isStationary(), and main().
int transferOperator::printFinalDist (const char * path, const char * dataFormat = "%lf")
#include <include/transferOperator.hpp>
Print final distribution to file.
Parameters
[in] path Path to the file in which to print.
[in] dataFormat Format in which to print each element.
Returns
Status.
Definition at line 497 of file transferOperator.hpp.
References transferOperator::finalDist.
Referenced by transferOperator::isStationary(), and main().
int transferOperator::printForwardTransition (const char * path, const char * dataFormat = "%lf")
#include <include/transferOperator.hpp>
Print forward transition matrix to file in coordinate format with header (see transferOperator.hpp)
Parameters
[in] path Path to the file in which to print.
[in] dataFormat Format in which to print each element.
Returns
Status.
Definition at line 397 of file transferOperator.hpp.
References transferOperator::P.
Referenced by transferOperator::isStationary(), and main().
int transferOperator::printInitDist (const char * path, const char * dataFormat = "%lf")
#include <include/transferOperator.hpp>
Print initial distribution to file.
Parameters
[in] path Path to the file in which to print.
[in] dataFormat Format in which to print each element.
Returns
Status.
Definition at line 470 of file transferOperator.hpp.
References transferOperator::initDist.
Referenced by transferOperator::isStationary(), and main().
int transferOperator::scanBackwardTransition (const char * path)
#include <include/transferOperator.hpp>
Scan backward transition matrix from file in coordinate format with header. (see transferOperator.hpp). No preliminary memory allocation needed but the grid size should be set. Previously allocated memory should first be freed to avoid memory leak.
Parameters
[in] path Path to the file in which to scan.
Returns
0 in success, EXIT_FAILURE otherwise.
Scan, summing if duplicate
Check if matrix dimension consistent with grid size
Compress
Definition at line 577 of file transferOperator.hpp.
References transferOperator::Q.
Referenced by transferOperator::isStationary(), and main().
int transferOperator::scanFinalDist (const char * path)
#include <include/transferOperator.hpp>
Scan final distribution from file. No preliminary memory allocation needed but the grid size should be set. Previously allocated memory should first be freed to avoid memory leak.
Parameters
[in] path Path to the file in which to scan.
Returns
0 in success, EXIT_FAILURE otherwise.
Scan after preallocating
Definition at line 665 of file transferOperator.hpp.
References transferOperator::finalDist.
Referenced by transferOperator::isStationary(), and main().
int transferOperator::scanForwardTransition (const char * path)
#include <include/transferOperator.hpp>
Scan forward transition matrix from file in coordinate format with header. (see transferOperator.hpp). No preliminary memory allocation needed but the grid size should be set. Previously allocated memory should first be freed to avoid memory leak.
Parameters
[in] path Path to the file in which to scan.
Returns
0 in success, EXIT_FAILURE otherwise.
Scan, summing if duplicate
Check if matrix dimension consistent with grid size
Compress
Definition at line 526 of file transferOperator.hpp.
References transferOperator::P.
Referenced by transferOperator::isStationary(), and main().
int transferOperator::scanInitDist (const char * path)
#include <include/transferOperator.hpp>
Scan initial distribution from file. No preliminary memory allocation needed but the grid size should be set. Previously allocated memory should first be freed to avoid memory leak.
Parameters
[in] path Path to the file in which to scan.
Returns
0 in success, EXIT_FAILURE otherwise.
Scan after preallocating
Definition at line 637 of file transferOperator.hpp.
References transferOperator::initDist.
Referenced by transferOperator::isStationary(), and main().
void transferSpectrum::sort ()
#include <include/transferSpectrum.hpp>
Sort by largest maginitude.
Test that both forward and backward eigen problems have been solved.
Sort forward eigenvalues by decreasing absolute value
Sort backward vectors by correspondance to forward counterparts (since different eigenvalues may have the same magnitude).
Get distance from eigenvalue
Sort backward eigenvalue and eigenvector
Free
Mark that sorting has been performed
Definition at line 432 of file transferSpectrum.hpp.
References transferSpectrum::EigValBackward, transferSpectrum::EigValForward, transferSpectrum::EigVecBackward, transferSpectrum::EigVecForward, gsl_permute_matrix_complex(), gsl_vector_complex_abs(), and gsl_vector_complex_min_index().
Referenced by transferSpectrum::makeBiorthonormal().
transferOperator::transferOperator (const gsl_matrix_uint * gridMem, const size_t N_, const bool stationary_ = false)
#include <include/transferOperator.hpp>
Construct transferOperator by calculating the forward and backward transition matrices and distributions from the grid membership matrix.
Parameters
[in] gridMem GSL grid membership matrix.
[in] N_ Number of grid boxes.
[in] stationary_ Whether the system is stationary (in which case and no need to calculate the backward transition matrix).
Definition at line 178 of file transferOperator.hpp.
transferOperator::transferOperator (const gsl_matrix * initStates, const gsl_matrix * finalStates, const Grid * grid, const bool stationary_ = false)
#include <include/transferOperator.hpp>
Construct transferOperator by calculating the forward and backward transition matrices and distributions from the initial and final states of trajectories.
Parameters
[in] initStates GSL matrix of initial states.
[in] finalStates GSL matrix of final states.
[in] grid Pointer to Grid object.
[in] stationary_ Whether the system is stationary (in which case and no need to calculate the backward transition matrix).
Definition at line 197 of file transferOperator.hpp.
References getGridMemMatrix().
transferOperator::transferOperator (const gsl_matrix * states, const Grid * grid, size_t tauStep)
#include <include/transferOperator.hpp>
Construct transferOperator calculating the forward and backward transition matrices and distributions from a single long trajectory, for a given grid and lag.
Parameters
[in] states GSL matrix of states for each time step.
[in] grid Pointer to Grid object.
[in] tauStep Lag used to calculate the transitions.
Definition at line 221 of file transferOperator.hpp.
References getGridMemMatrix().
transferSpectrum::transferSpectrum (const int nev_, const transferOperator * transferOp_, const configAR cfgAR = defaultCfgAR)
#include <include/transferSpectrum.hpp>
Constructor allocating space for a given number of eigenvalues and vectors for a given transferOperator.
Parameters
[in] nev_ Number of eigenvalues and eigenvectors for which to allocate.
[in] transferOp_ Pointer to the transferOperator on which to solve the eigen problem.
[in] cfgAR Configuration data used by ARPACK++ for the eigen problem.
Definition at line 188 of file transferSpectrum.hpp.
void transferSpectrum::writeSpectrum (const char * EigValForwardFile, const char * EigVecForwardFile, const char * EigValBackwardFile, const char * EigVecBackwardFile) const
#include <include/transferSpectrum.hpp>
Write complex eigenvalues and eigenvectors of forward and backward transition matrices.
Parameters
[in] EigValForwardFile File name of the file to print forward eigenvalues.
[in] EigVecForwardFile File name of the file to print forward eigenvectors.
[in] EigValBackwardFile File name of the file to print backward eigenvalues.
[in] EigVecBackwardFile File name of the file to print backward eigenvectors.
Returns
Exit status.
Write forward eigenvalues and eigenvectors
Write backward eigenvalues and eigenvectors
Definition at line 628 of file transferSpectrum.hpp.
References transferSpectrum::writeSpectrumBackward(), and transferSpectrum::writeSpectrumForward().
void writeSpectrumAR (FILE * fEigVal, FILE * fEigVec, const gsl_vector_complex * EigVal, const gsl_matrix_complex * EigVec)
#include <include/transferSpectrum.hpp>
Write complex eigenvalues and eigenvectors obtained as arrays from ARPACK++.
Parameters
[in] fEigVal File descriptor for eigenvalues.
[in] fEigVec File descriptor for eigenvectors.
[in] EigVal Array of eigenvalues real parts.
[in] EigVec Array of eigenvectors.
Check for printing errors
Check for printing errors
Definition at line 789 of file transferSpectrum.hpp.
Referenced by transferSpectrum::setConfig(), transferSpectrum::writeSpectrumBackward(), and transferSpectrum::writeSpectrumForward().
void transferSpectrum::writeSpectrumBackward (const char * EigValBackwardFile, const char * EigVecBackwardFile) const
#include <include/transferSpectrum.hpp>
Write eigenvalues and eigenvectors of backward transition matrix.
Parameters
[in] EigValBackwardFile File name of the file to print backward eigenvalues.
[in] EigVecBackwardFile File name of the file to print backward eigenvectors.
Returns
Exit status.
Open files back backward
Write backward
Close
Definition at line 590 of file transferSpectrum.hpp.
References transferSpectrum::EigValBackward, transferSpectrum::EigVecBackward, and writeSpectrumAR().
Referenced by main(), and transferSpectrum::writeSpectrum().
void transferSpectrum::writeSpectrumForward (const char * EigValForwardFile, const char * EigVecForwardFile) const
#include <include/transferSpectrum.hpp>
Write eigenvalues and eigenvectors of forward transition matrix.
Parameters
[in] EigValForwardFile File name of the file to print forward eigenvalues.
[in] EigVecForwardFile File name of the file to print forward eigenvectors.
Returns
Exit status.
Open files for forward
Write forward
Close
Definition at line 555 of file transferSpectrum.hpp.
References transferSpectrum::EigValForward, transferSpectrum::EigVecForward, and writeSpectrumAR().
Referenced by main(), and transferSpectrum::writeSpectrum().
transferOperator::~transferOperator ()
#include <include/transferOperator.hpp>
Destructor of transferOperator: desallocate all pointers.
Definition at line 238 of file transferOperator.hpp.
References transferOperator::finalDist, getTransitionCountTriplet(), gsl_spmatrix_div_cols(), gsl_vector_normalize(), transferOperator::initDist, transferOperator::P, and transferOperator::Q.
Referenced by transferOperator::transferOperator().
transferSpectrum::~transferSpectrum ()
#include <include/transferSpectrum.hpp>
Destructor desallocates.
Free memory for forward eigenvalues and eigenvectors
Free memory for backward eigenvalues and eigenvectors
Definition at line 198 of file transferSpectrum.hpp.
References transferSpectrum::EigValBackward, transferSpectrum::EigValForward, transferSpectrum::EigVecBackward, and transferSpectrum::EigVecForward.
Variable Documentation
configAR defaultCfgAR = {"LM", 0, 0., 0, NULL, true}
#include <include/transferSpectrum.hpp>
Declare default structure looking for largest magnitude eigenvalues
Definition at line 52 of file transferSpectrum.hpp.