ergoPack: Gridding
Gridding
Files
file ergoGrid.hpp
Various grid definitions used for Galerkin approximation.
Classes
class Grid
Grid class.
class CurvilinearGrid
Curvilinear Grid.
class RegularGrid
Regular grid.
class PolarGrid
Polar grid.
Functions
gsl_matrix_uint * getGridMemMatrix (const gsl_matrix *initStates, const gsl_matrix *finalStates, const Grid *grid)
Get membership matrix from initial and final states for a grid.
gsl_matrix_uint * getGridMemMatrix (const gsl_matrix *states, const Grid *grid, const size_t tauStep)
Get the grid membership vector from a single long trajectory.
gsl_vector_uint * getGridMemVector (const gsl_matrix *states, const Grid *grid)
Get the grid membership matrix from a single long trajectory.
gsl_matrix_uint * memVector2memMatrix (const gsl_vector_uint *gridMemVect, size_t tauStep)
Get the grid membership matrix from the membership vector for a given lag.
gsl_matrix_uint * memVectorList2memMatrix (const std::vector< gsl_vector_uint * > *memList, size_t tauStep)
Concatenate a list of membership vectors into one membership matrix.
void getDensityMLE (const gsl_vector_uint *gridMemVect, const Grid *grid, gsl_vector *density)
Get MLE of a density from the grid membership vector of a time series.
gsl_matrix_uint * memVector2memMatrix (gsl_vector_uint *gridMemVect, size_t tauStep)
RegularGrid::RegularGrid (const size_t inx, const double nSTDLow, const double nSTDHigh, const gsl_matrix *states)
Construct a uniform rectangular grid with same dimensions adapted to time series.
RegularGrid::RegularGrid (const gsl_vector_uint *nx_, const gsl_vector *xmin, const gsl_vector *xmax)
Construct a uniform rectangular grid with different dimensions.
RegularGrid::RegularGrid (const size_t dim_, const size_t inx, const double xmin, const double xmax)
Construct a uniform rectangular grid with same dimensions.
RegularGrid::RegularGrid (const gsl_vector_uint *nx_, const gsl_vector *nSTDLow, const gsl_vector *nSTDHigh, const gsl_matrix *states)
Construct a uniform rectangular grid adapted to time series.
PolarGrid::PolarGrid (const size_t nLevels, const size_t nSectors, const Grid *support, const gsl_matrix *states)
Construct a polar grid adapted to the time series.
int RegularGrid::printGrid (const char *path, const char *dataFormat, const bool verbose) const
Print regular grid to file.
size_t RegularGrid::getBoxMembership (const gsl_vector *state) const
Get membership of a state to a box.
void RegularGrid::getBoxPosition (const size_t index, gsl_vector *position) const
Get center of position of grid box.
PolarGrid::~PolarGrid ()
Destructor desallocating memory.
Detailed Description
Function Documentation
size_t RegularGrid::getBoxMembership (const gsl_vector * state) const virtual
#include <include/ergoGrid.hpp>
Get membership to a grid box of a single realization.
Parameters
[in] state Vector of a single state.
Returns
Box index to which the state belongs.
Implements Grid.
Definition at line 540 of file ergoGrid.hpp.
References Grid::dim, and Grid::N.
void RegularGrid::getBoxPosition (const size_t index, gsl_vector * position) const virtual
#include <include/ergoGrid.hpp>
Get position of grid box.
Parameters
[in] index Index of box for which to get the position.
[out] position Position of the box.
Implements Grid.
Definition at line 583 of file ergoGrid.hpp.
References Grid::dim, and Grid::getN().
void getDensityMLE (const gsl_vector_uint * gridMemVect, const Grid * grid, gsl_vector * density)
#include <include/ergoGrid.hpp>
Get Maximum Likelihood Estimator of a density from the membership vector of a time series to a grid.
Parameters
[in] gridMemVect Grid membership vector.
[in] grid Grid.
[out] density MLE of the density on the grid.
Definition at line 950 of file ergoGrid.hpp.
References Grid::getN(), Grid::N, and nt.
Referenced by PolarGrid::PolarGrid(), and PolarGrid::printGrid().
gsl_matrix_uint * getGridMemMatrix (const gsl_matrix * initStates, const gsl_matrix * finalStates, const Grid * grid)
#include <include/ergoGrid.hpp>
Get membership matrix from initial and final states for a grid.
Parameters
[in] initStates GSL matrix of initial states.
[in] finalStates GSL matrix of final states.
[in] grid Pointer to Grid object.
Returns
GSL grid membership matrix.
Definition at line 779 of file ergoGrid.hpp.
References Grid::dim, Grid::getBoxMembership(), and Grid::getN().
Referenced by PolarGrid::printGrid(), and transferOperator::transferOperator().
gsl_matrix_uint * getGridMemMatrix (const gsl_matrix * states, const Grid * grid, const size_t tauStep)
#include <include/ergoGrid.hpp>
Get the grid membership matrix from a single long trajectory.
Parameters
[in] states GSL matrix of states for each time step.
[in] grid Pointer to Grid object.
[in] tauStep Lag used to calculate the transitions.
Returns
GSL grid membership matrix.
Definition at line 890 of file ergoGrid.hpp.
References getGridMemVector(), and memVector2memMatrix().
gsl_vector_uint * getGridMemVector (const gsl_matrix * states, const Grid * grid)
#include <include/ergoGrid.hpp>
Get the grid membership vector from a single long trajectory.
Parameters
[in] states GSL matrix of states for each time step.
[in] grid Pointer to Grid object.
Returns
GSL grid membership vector.
Definition at line 827 of file ergoGrid.hpp.
References Grid::dim, and Grid::getBoxMembership().
Referenced by getGridMemMatrix(), main(), PolarGrid::PolarGrid(), and PolarGrid::printGrid().
gsl_matrix_uint* memVector2memMatrix (gsl_vector_uint * gridMemVect, size_t tauStep)
#include <include/ergoGrid.hpp>
Get the grid membership matrix from the membership vector for a given lag.
Parameters
[in] gridMemVect Grid membership vector of a long trajectory for a grid.
[in] tauStep Lag used to calculate the transitions.
Returns
GSL grid membership matrix.
Definition at line 866 of file ergoGrid.hpp.
gsl_matrix_uint * memVectorList2memMatrix (const std::vector< gsl_vector_uint * > * memList, size_t tauStep)
#include <include/ergoGrid.hpp>
Concatenate a list of membership vectors into one membership matrix.
Parameters
[in] memList STD vector of membership Vectors each of them associated with a single long trajectory.
[in] tauStep Lag used to calculate the transitions.
Returns
GSL grid membership matrix.
Definition at line 912 of file ergoGrid.hpp.
References memVector2memMatrix().
Referenced by PolarGrid::printGrid().
PolarGrid::PolarGrid (const size_t nLevels_, const size_t nSectors_, const Grid * support, const gsl_matrix * states)
#include <include/ergoGrid.hpp>
Construct a polar grid adapted to the time series (yet, only for 2D).
Parameters
[in] nLevels_ Number of levels for the grid
[in] nSectors_ Number of sectors for the grid
[in] support Rectangular grid used to calculate the density.
[in] states Trajectory to which to adapt the grid.
The state is outside the support grid, mark it outside the polar grid
Definition at line 339 of file ergoGrid.hpp.
References Grid::dim, getDensityMLE(), getGridMemVector(), Grid::getN(), gsl_matrix_get_max(), gsl_matrix_get_mean(), gsl_matrix_get_min(), gsl_matrix_get_std(), Grid::N, nSTDHigh, nSTDLow, and nx.
int RegularGrid::printGrid (const char * path, const char * dataFormat = "%lf", const bool verbose = false) const virtual
#include <include/ergoGrid.hpp>
Print the grid to file.
Parameters
[in] path Path to the file in which to print.
[in] dataFormat Format in which to print each element.
[in] verbose If true, also print to the standard output.
Returns
Status.
Check for printing errors
Implements Grid.
Definition at line 487 of file ergoGrid.hpp.
References Grid::dim.
RegularGrid::RegularGrid (const gsl_vector_uint * nx_, const gsl_vector * xmin, const gsl_vector * xmax)
#include <include/ergoGrid.hpp>
Construct a uniform rectangular grid with specific bounds for each dimension.
Parameters
[in] nx_ Vector giving the number of boxes for each dimension.
[in] xmin Vector giving the minimum box limit for each dimension.
[in] xmax Vector giving the maximum box limit for each dimension.
Definition at line 272 of file ergoGrid.hpp.
RegularGrid::RegularGrid (const size_t dim_, const size_t inx, const double dxmin, const double dxmax)
#include <include/ergoGrid.hpp>
Construct a uniform rectangular grid with same bounds for each dimension.
Parameters
[in] dim_ Number of dimensions.
[in] inx Number of boxes, identically for each dimension.
[in] dxmin Minimum box limit, identically for each dimension.
[in] dxmax Maximum box limit, identically for each dimension.
Definition at line 290 of file ergoGrid.hpp.
RegularGrid::RegularGrid (const gsl_vector_uint * nx_, const gsl_vector * nSTDLow, const gsl_vector * nSTDHigh, const gsl_matrix * states)
#include <include/ergoGrid.hpp>
Construct a uniform rectangular grid adapted to the time series.
Parameters
[in] nx_ Vector giving the number of boxes for each dimension.
[in] nSTDLow Vector giving the number of standard deviations to span away from the mean state from below.
[in] nSTDHigh Vector giving the number of standard deviations to span away from the mean state from above.
[in] states Time series.
Definition at line 320 of file ergoGrid.hpp.
RegularGrid::RegularGrid (const size_t inx, const double nSTDLow, const double nSTDHigh, const gsl_matrix * states)
#include <include/ergoGrid.hpp>
Construct a uniform rectangular grid with same dimensions adapted to the time series.
Parameters
[in] inx Number of boxes for each dimension.
[in] nSTDLow Number of standard deviations to span away from the mean state from below.
[in] nSTDHigh Number of standard deviations to span away from the mean state from above.
[in] states Time series.
Definition at line 231 of file ergoGrid.hpp.
References Grid::dim.
PolarGrid::~PolarGrid ()
#include <include/ergoGrid.hpp>
Destructor desallocating memory.
Definition at line 617 of file ergoGrid.hpp.
References A, Grid::dim, Grid::getBoxPosition(), getEOF(), Grid::getN(), and gsl_vector_max_index_among().