ergoPack: Simulating
Simulating
Files
file SDDESolvers.hpp
Solve Stochastic Delay Differential Equations.
file SDESolvers.hpp
Solve Stocahstic Differential Equations.
Classes
class vectorField
Abstract class defining a vector field.
class vectorFieldDelay
Abstract delayed vector field class.
class numericalSchemeSDDE
Abstract SDDE numerical scheme class.
class EulerMaruyamaSDDE
Euler-Maruyama SDDE numerical scheme.
class modelSDDE
Numerical SDDE model class.
class vectorFieldStochastic
Abstract stochastic vector field class.
class additiveWiener
Additive Wiener process.
class multiplicativeLinearWiener
Linear multiplicative Wiener process.
class numericalSchemeStochastic
Abstract stochastic numerical scheme class.
class EulerMaruyama
Euler-Maruyama stochastic numerical scheme. Euler-Maruyama stochastic numerical scheme.
class modelStochastic
Numerical stochastic model class.
Functions
vectorFieldDelay::vectorFieldDelay (std::vector< vectorField * > *fields_, const gsl_vector_uint *delays_)
Constructor setting the dimension and allocating.
virtual vectorFieldDelay::~vectorFieldDelay ()
Destructor freeing fields and workspace.
void vectorFieldDelay::evalField (gsl_matrix *state, gsl_vector *field)
Method for evaluating the delayed vector field at a given state.
void numericalSchemeSDDE::updateHistoric (gsl_matrix *currentState)
Update past states of a historic by one step.
void EulerMaruyamaSDDE::stepForward (vectorFieldDelay *delayedField, vectorFieldStochastic *stocField, gsl_matrix *currentState)
Virtual method to integrate the stochastic model one step forward.
void modelSDDE::stepForward ()
One time-step forward integration of the modelSDDE.
gsl_matrix * modelSDDE::integrateForward (const double length, const double spinup, const size_t sampling)
Integrate the modelSDDE forward for a given period.
void additiveWiener::evalField (gsl_vector *state, gsl_vector *field)
Evaluate the linear vector field at a given state.
void multiplicativeLinearWiener::evalField (gsl_vector *state, gsl_vector *field)
Evaluate the linear vector field at a given state.
void EulerMaruyama::stepForward (vectorField *field, vectorFieldStochastic *stocField, gsl_vector *currentState)
Virtual method to integrate the stochastic model one step forward.
void modelStochastic::stepForward ()
One time-step forward integration of the modelStochastic.
gsl_matrix * modelStochastic::integrateForward (const double length, const double spinup, const size_t sampling)
Integrate the modelStochastic forward for a given period.
Detailed Description
Function Documentation
void vectorFieldDelay::evalField (gsl_matrix * state, gsl_vector * field)
#include <include/SDDESolvers.hpp>
Evaluate the delayed vector field from fields for each delay.
Parameters
[in] state State at which to evaluate the vector field.
[out] field Vector resulting from the evaluation of the vector field.
Add delayed drifts
Definition at line 263 of file SDDESolvers.hpp.
References vectorFieldDelay::delays, vectorFieldDelay::fields, vectorFieldDelay::nDelays, and vectorFieldDelay::work.
Referenced by vectorFieldDelay::getDelays(), and EulerMaruyamaSDDE::stepForward().
gsl_matrix * modelSDDE::integrateForward (const double length, const double spinup, const size_t sampling)
#include <include/SDDESolvers.hpp>
Integrate the SDDE model forward for a given period.
Parameters
[in] length Duration of the integration.
[in] spinup Initial integration period to remove.
[in] sampling Time step at which to save states.
Returns
Matrix to record the states.
Definition at line 382 of file SDDESolvers.hpp.
References vectorFieldDelay::dim, and nt.
Referenced by main().
gsl_matrix * modelStochastic::integrateForward (const double length, const double spinup, const size_t sampling)
#include <include/SDESolvers.hpp>
Integrate the stochastic model forward for a given period.
Parameters
[in] length Duration of the integration.
[in] spinup Initial integration period to remove.
[in] sampling Time step at which to save states.
Returns
Matrix to record the states.
Definition at line 318 of file SDESolvers.hpp.
References vectorField::dim, and nt.
Referenced by main().
void EulerMaruyamaSDDE::stepForward (vectorFieldDelay * delayedField, vectorFieldStochastic * stocField, gsl_matrix * currentState) virtual
#include <include/SDDESolvers.hpp>
Integrate SDDE one step forward for a given vector field and state using the Euler Maruyama scheme.
Parameters
[in] delayedField Delayed vector fields to evaluate.
[in] stocField stochastic vector field to evaluate.
[in,out] currentState Current state to update by one time step.
Evaluate drift
Update historic
Add diffusion at present state
Implements numericalSchemeSDDE.
Definition at line 322 of file SDDESolvers.hpp.
References dt, vectorFieldStochastic::evalField(), vectorFieldDelay::evalField(), and vectorFieldDelay::work.
void EulerMaruyama::stepForward (vectorField * field, vectorFieldStochastic * stocField, gsl_vector * currentState) virtual
#include <include/SDESolvers.hpp>
Integrate stochastically one step forward for a given vector field and state using the Euler Maruyama scheme.
Parameters
[in] field Vector field to evaluate.
[in] stocField Stochastic vector field to evaluate.
[in,out] currentState Current state to update by one time step.
Implements numericalSchemeStochastic.
Definition at line 275 of file SDESolvers.hpp.
References dt, vectorField::evalField(), and vectorFieldStochastic::evalField().
void modelSDDE::stepForward ()
#include <include/SDDESolvers.hpp>
Integrate one step forward the SDDE model with the numerical scheme.
Definition at line 365 of file SDDESolvers.hpp.
void modelStochastic::stepForward ()
#include <include/SDESolvers.hpp>
Integrate one step forward the stochastic model with the numerical scheme.
Definition at line 301 of file SDESolvers.hpp.
void numericalSchemeSDDE::updateHistoric (gsl_matrix * currentState) protected
#include <include/SDDESolvers.hpp>
Update past states of historic by one time step.
Parameters
[in,out] currentState Historic to update.
Definition at line 298 of file SDDESolvers.hpp.
References vectorFieldDelay::delayMax.
vectorFieldDelay::vectorFieldDelay (std::vector< vectorField * > * fields_, const gsl_vector_uint * delays_)
#include <include/SDDESolvers.hpp>
Constructor for a delayed vector field.
Parameters
[in] fields_ Vector of vector fields for each delay.
[in] delays_ Delays associated with each vector field.
Definition at line 226 of file SDDESolvers.hpp.
References vectorFieldDelay::delays, vectorFieldDelay::dim, vectorFieldDelay::nDelays, and vectorFieldDelay::work.
vectorFieldDelay::~vectorFieldDelay () virtual
#include <include/SDDESolvers.hpp>
Destructor for a delayed vector field, desallocating.
Definition at line 243 of file SDDESolvers.hpp.
References vectorFieldDelay::delays, vectorFieldDelay::fields, vectorFieldDelay::nDelays, and vectorFieldDelay::work.