ergoPack: include/gsl_extension.h File Reference
gsl_extension.h File Reference
Extend GSL with utility functions.
#include <gsl/gsl_vector.h>
#include <gsl/gsl_matrix.h>
#include <gsl/gsl_errno.h>
#include <math.h>
Functions
int gsl_vector_sqrt (gsl_vector *v)
Get the square root of the elements of a vector.
int gsl_vector_normalize (gsl_vector *v)
Normalize vector by the sum of its elements.
double gsl_vector_get_sum (const gsl_vector *v)
Get sum of vector elements.
double gsl_vector_get_prod (const gsl_vector *v)
Get product of vector elements.
double gsl_vector_uint_get_prod (const gsl_vector_uint *v)
Get product of vector elements.
double gsl_vector_get_mean (const gsl_vector *v)
Get the mean over the elements of a vector.
double gsl_vector_get_var (const gsl_vector *v)
Get the variance over the elements of a vector.
double gsl_vector_get_std (const gsl_vector *v)
Get the standard deviation over the elements of a vector.
size_t gsl_vector_max_index_among (gsl_vector *v, gsl_vector_uint *marker)
Get index of maximum of vector among marked elements.
int gsl_vector_linspace (gsl_vector *v, const double lower, const double upper, const size_t n)
Get vector of a given number equally-spaced numbers between two bounds.
gsl_vector * gsl_matrix_get_rowsum (const gsl_matrix *m)
Get the sum of the elements of a matrix over each row.
gsl_vector * gsl_matrix_get_colsum (const gsl_matrix *m)
Get the sum of the elements of a matrix over each column.
gsl_vector * gsl_matrix_get_mean (const gsl_matrix *m, const size_t axis)
Get the mean over the elements of a matrix along a given axis.
gsl_vector * gsl_matrix_get_variance (const gsl_matrix *m, const size_t axis)
Get the variance over the elements of a matrix along a given axis.
gsl_vector * gsl_matrix_get_std (const gsl_matrix *m, const size_t axis)
Get the standard deviation over the elements of a matrix along a given axis.
size_t gsl_vector_max_index_among (const gsl_vector *v, const gsl_vector_uint *marker)
int gsl_vector_linspace (gsl_vector *v, const double lower, const double upper)
gsl_vector * gsl_matrix_get_var (const gsl_matrix *m, const size_t axis)
Detailed Description
Extend GSL with utility functions.
Definition in file gsl_extension.h.
Function Documentation
gsl_vector * gsl_matrix_get_colsum (const gsl_matrix * m)
Get the sum of the elements of a matrix over each column.
Parameters
[in] m Matrix over which to sum.
Returns
Vector of the sum of the columns.
Definition at line 284 of file gsl_extension.h.
References gsl_vector_get_sum().
Referenced by gsl_matrix_get_mean().
gsl_vector * gsl_matrix_get_mean (const gsl_matrix * m, const size_t axis)
Get the mean of the elements of a matrix along a given axis.
Parameters
[in] m Matrix over which to calculate the mean.
[in] axis Axis over which to calculate the mean (0: along columns, 1: along rows).
Returns
Vector of with the means.
Definition at line 307 of file gsl_extension.h.
References gsl_matrix_get_colsum(), and gsl_matrix_get_rowsum().
Referenced by getEOF(), gsl_matrix_get_var(), and PolarGrid::PolarGrid().
gsl_vector * gsl_matrix_get_rowsum (const gsl_matrix * m)
Get the sum of the elements of a matrix over each row.
Parameters
[in] m Matrix over which to sum.
Returns
Vector of the sum of the rows.
Definition at line 263 of file gsl_extension.h.
References gsl_vector_get_sum().
Referenced by gsl_matrix_get_mean().
gsl_vector * gsl_matrix_get_std (const gsl_matrix * m, const size_t axis)
Get the standard deviation of the elements of a matrix along a given axis.
Parameters
[in] m Matrix over which to calculate the standard deviation.
[in] axis Axis over which to calculate the standard deviation (0: along columns, 1: along rows).
Returns
Vector of with the standard deviation.
Definition at line 369 of file gsl_extension.h.
References gsl_matrix_get_var(), and gsl_vector_sqrt().
Referenced by PolarGrid::PolarGrid().
gsl_vector* gsl_matrix_get_var (const gsl_matrix * m, const size_t axis)
Get the variance of the elements of a matrix along a given axis.
Parameters
[in] m Matrix over which to calculate the variance.
[in] axis Axis over which to calculate the variance (0: along columns, 1: along rows).
Returns
Vector of with the variance.
Definition at line 337 of file gsl_extension.h.
References gsl_matrix_get_mean().
Referenced by gsl_matrix_get_std().
double gsl_vector_get_mean (const gsl_vector * v)
Get the mean of the elements of a vector
Parameters
[in] v Vector over which to calculate the mean.
Returns
Mean of the vector.
Definition at line 147 of file gsl_extension.h.
References gsl_vector_get_sum().
Referenced by gsl_vector_get_var().
double gsl_vector_get_prod (const gsl_vector * v)
Get product of vector elements.
Parameters
[in] v Vector from which to multiply the elements.
Returns
Product of vector elements.
Definition at line 113 of file gsl_extension.h.
double gsl_vector_get_std (const gsl_vector * v)
Get the standard deviation of the elements of a vector
Parameters
[in] v Vector over which to calculate the standard deviation.
Returns
Standard Deviation of the vector.
Definition at line 188 of file gsl_extension.h.
References gsl_vector_get_var().
double gsl_vector_get_sum (const gsl_vector * v)
Get sum of vector elements.
Parameters
[in] v Vector from which to sum the elements.
Returns
Sum of vector elements.
Definition at line 96 of file gsl_extension.h.
Referenced by gsl_matrix_get_colsum(), gsl_matrix_get_rowsum(), gsl_vector_get_mean(), and gsl_vector_normalize().
double gsl_vector_get_var (const gsl_vector * v)
Get the variance of the elements of a vector
Parameters
[in] v Vector over which to calculate the variance.
Returns
Variance of the vector.
Definition at line 159 of file gsl_extension.h.
References gsl_vector_get_mean().
Referenced by gsl_vector_get_std().
int gsl_vector_linspace (gsl_vector * v, const double lower, const double upper)
Get vector of a given number equally-spaced numbers between two bounds.
Parameters
[out] v Vector for which to set the elements.
[in] lower Lower bound.
[in] upper Upper bound.
Definition at line 238 of file gsl_extension.h.
size_t gsl_vector_max_index_among (const gsl_vector * v, const gsl_vector_uint * marker)
Get index of maximum of vector among marked elements.
Parameters
[in] v Vector for which to find the maximum.
[in] marker Boolean vector marking the elements among which to look for the maximum.
Returns
Index of the maximum.
Definition at line 201 of file gsl_extension.h.
int gsl_vector_normalize (gsl_vector * v)
Normalize vector by the sum of its elements.
Parameters
[in] v Vector to normalize.
Definition at line 79 of file gsl_extension.h.
References gsl_vector_get_sum().
Referenced by filterStochasticMatrix(), and transferOperator::~transferOperator().
int gsl_vector_sqrt (gsl_vector * v)
Get the square root of the elements of a vector.
Parameters
[in,out] v Vector for which to calculate the square root.
Returns
Exit status.
Definition at line 64 of file gsl_extension.h.
Referenced by gsl_matrix_get_std().
double gsl_vector_uint_get_prod (const gsl_vector_uint * v)
Get product of vector elements.
Parameters
[in] v Vector from which to multiply the elements.
Returns
Product of vector elements.
Definition at line 130 of file gsl_extension.h.