ergoPack: include/gsl_extension.hpp File Reference
gsl_extension.hpp File Reference
Extend GSL with utility functions.
#include <cstdio>
#include <gsl/gsl_complex.h>
#include <gsl/gsl_complex_math.h>
#include <gsl/gsl_vector.h>
#include <gsl/gsl_matrix.h>
#include <gsl/gsl_spmatrix.h>
#include <gsl/gsl_permutation.h>
#include <gsl/gsl_errno.h>
#include <math.h>
Functions
int gsl_vector_sqrt (gsl_vector *v)
Get the square root of the elements of a vector.
int gsl_vector_normalize (gsl_vector *v)
Normalize vector by the sum of its elements.
double gsl_vector_get_sum (const gsl_vector *v)
Get sum of vector elements.
double gsl_vector_get_inner_product (const gsl_vector *v, const gsl_vector *w, const gsl_vector *mu=NULL)
Get inner product of two vectors for a given measure.
double gsl_vector_get_norm (const gsl_vector *v, const gsl_vector *mu=NULL)
Get norm of a vector for a given measure.
double gsl_vector_get_prod (const gsl_vector *v)
Get product of vector elements.
double gsl_vector_uint_get_prod (const gsl_vector_uint *v)
Get product of vector elements.
double gsl_vector_get_mean (const gsl_vector *v)
Get the mean over the elements of a vector.
double gsl_vector_get_var (const gsl_vector *v)
Get the variance over the elements of a vector.
double gsl_vector_get_std (const gsl_vector *v)
Get the standard deviation over the elements of a vector.
size_t gsl_vector_max_index_among (gsl_vector *v, gsl_vector_uint *marker)
Get index of maximum of vector among marked elements.
int gsl_vector_linspace (gsl_vector *v, const double lower, const double upper, const size_t n)
Get vector of a given number equally-spaced numbers between two bounds.
int gsl_vector_complex_memcpy_real (gsl_vector_complex *dst, const gsl_vector *src)
Copy vector to real part of complex vector.
int gsl_vector_complex_memcpy_imag (gsl_vector_complex *dst, const gsl_vector *src)
Copy vector to imaginary part of complex vector.
void gsl_vector_complex_scale_real (gsl_vector_complex *v, const double a)
Scale a complex vector with a real number.
void gsl_vector_complex_log (gsl_vector_complex *res, const gsl_vector_complex *v)
Get complex logarithm of complex vector.
gsl_vector * gsl_vector_complex_abs (const gsl_vector_complex *v)
Get absolute values of complex vector.
gsl_complex gsl_vector_complex_max (const gsl_vector_complex *v)
Find the maximum in absolute value of a complex vector.
size_t gsl_vector_complex_max_index (const gsl_vector_complex *v)
Find the index of the maximum in absolute value of a complex vector.
gsl_complex gsl_vector_complex_min (const gsl_vector_complex *v)
Find the minimum in absolute value of a complex vector.
size_t gsl_vector_complex_min_index (const gsl_vector_complex *v)
Find the index of the minimum in absolute value of a complex vector.
gsl_complex gsl_vector_complex_get_inner_product (const gsl_vector_complex *v, const gsl_vector_complex *w, const gsl_vector *mu=NULL)
Calculate inner product between two complex vectors for a given measure.
double gsl_vector_complex_get_norm (const gsl_vector_complex *v, const gsl_vector *mu=NULL)
Calculate the norm of a complex vector for a given measure .
int gsl_permute_matrix_complex (const gsl_permutation *p, gsl_matrix_complex *m, const size_t axis)
Permute rows or columns of a matrix.
int gsl_matrix_get_rowsum (gsl_vector *sum, const gsl_matrix *m)
Get the sum of the elements of a matrix over each row.
int gsl_matrix_get_colsum (gsl_vector *sum, const gsl_matrix *m)
Get the sum of the elements of a matrix over each column.
int gsl_matrix_get_mean (gsl_vector *mean, const gsl_matrix *m, const size_t axis)
Get the mean over the elements of a matrix along a given axis.
int gsl_matrix_get_variance (gsl_vector *var, const gsl_matrix *m, const size_t axis)
Get the variance over the elements of a matrix along a given axis.
int gsl_matrix_get_std (gsl_vector *std, const gsl_matrix *m, const size_t axis)
Get the standard deviation over the elements of a matrix along a given axis.
int gsl_matrix_get_min (gsl_vector *min, const gsl_matrix *m, const size_t axis)
Get the min over the elements of a matrix along a given axis.
int gsl_matrix_get_max (gsl_vector *max, const gsl_matrix *m, const size_t axis)
Get the max over the elements of a matrix along a given axis.
int gsl_spmatrix_get_rowsum (gsl_vector *sum, const gsl_spmatrix *m)
Get the sum of the elements of a compressed matrix over each row.
int gsl_spmatrix_get_colsum (gsl_vector *sum, const gsl_spmatrix *m)
Get the sum of the elements of a compressed matrix over each column.
double gsl_spmatrix_get_sum (const gsl_spmatrix *m)
Get the sum of the elements of a sparse matrix.
int gsl_spmatrix_div_rows (gsl_spmatrix *m, const gsl_vector *v, const double tol)
Divide each row of a compressed matrix by a vector.
int gsl_spmatrix_div_cols (gsl_spmatrix *m, const gsl_vector *v, const double tol)
Divide each column of a compressed matrix by a vector.
gsl_spmatrix * gsl_spmatrix_alloc2read (FILE *stream, const size_t type)
Pre-allocate a sparse matrix to read from a binary stream.
Detailed Description
Extend GSL with utility functions.
Definition in file gsl_extension.hpp.
Function Documentation
gsl_matrix_get_colsum()
int gsl_matrix_get_colsum (gsl_vector * sum, const gsl_matrix * m)
Get the sum of the elements of a matrix over each column.
Parameters
[out] sum Vector of the sum of the columns.
[in] m Matrix over which to sum.
Returns
Exit status.
Definition at line 654 of file gsl_extension.cpp.
References gsl_vector_get_sum().
Referenced by gsl_matrix_get_mean().
gsl_matrix_get_max()
int gsl_matrix_get_max (gsl_vector * max, const gsl_matrix * m, const size_t axis)
Get the max of the elements of a matrix along a given axis.
Parameters
[out] max Vector of the max.
[in] m Matrix over which to calculate the max.
[in] axis Axis over which to calculate the max (0: along columns, 1: along rows).
Returns
Exit status.
Definition at line 854 of file gsl_extension.cpp.
Referenced by RegularGrid::RegularGrid().
gsl_matrix_get_mean()
int gsl_matrix_get_mean (gsl_vector * mean, const gsl_matrix * m, const size_t axis)
Get the mean of the elements of a matrix along a given axis.
Parameters
[out] mean Vector of the means.
[in] m Matrix over which to calculate the mean.
[in] axis Axis over which to calculate the mean (0: along columns, 1: along rows).
Returns
Exit status.
Definition at line 677 of file gsl_extension.cpp.
References gsl_matrix_get_colsum(), and gsl_matrix_get_rowsum().
Referenced by getEOF(), gsl_matrix_get_var(), and RegularGrid::RegularGrid().
gsl_matrix_get_min()
int gsl_matrix_get_min (gsl_vector * min, const gsl_matrix * m, const size_t axis)
Get the min of the elements of a matrix along a given axis.
Parameters
[out] min Vector of the min.
[in] m Matrix over which to calculate the min.
[in] axis Axis over which to calculate the min (0: along columns, 1: along rows).
Returns
Exit status.
Definition at line 804 of file gsl_extension.cpp.
Referenced by RegularGrid::RegularGrid().
gsl_matrix_get_rowsum()
int gsl_matrix_get_rowsum (gsl_vector * sum, const gsl_matrix * m)
Get the sum of the elements of a matrix over each row.
Parameters
[out] sum Vector of the sum of the rows.
[in] m Matrix over which to sum.
Returns
Exit status.
Definition at line 633 of file gsl_extension.cpp.
References gsl_vector_get_sum().
Referenced by gsl_matrix_get_mean().
gsl_matrix_get_std()
int gsl_matrix_get_std (gsl_vector * std, const gsl_matrix * m, const size_t axis)
Get the standard deviation of the elements of a matrix along a given axis.
Parameters
[out] std Vector of the standard deviations.
[in] m Matrix over which to calculate the standard deviation.
[in] axis Axis over which to calculate the standard deviation (0: along columns, 1: along rows).
Returns
Exit status.
Definition at line 763 of file gsl_extension.cpp.
References gsl_matrix_get_var(), and gsl_vector_sqrt().
Referenced by RegularGrid::RegularGrid().
gsl_permute_matrix_complex()
int gsl_permute_matrix_complex (const gsl_permutation * p, gsl_matrix_complex * m, const size_t axis)
Permute rows (axis = 0) or columns (axis = 1) of a matrix according to permutation.
Parameters
[in] p Permutation.
[in,out] m Matrix to permute.
[in] axis Axis along which to permute.
Returns
Exit status.
Get size of axis along which to permute
Save matrix
Permute
Definition at line 573 of file gsl_extension.cpp.
Referenced by transferSpectrum::sort(), and sortSpectrum().
gsl_spmatrix_alloc2read()
gsl_spmatrix* gsl_spmatrix_alloc2read (FILE * stream, const size_t type)
Pre-allocate a sparse matrix in triplet format to read from a binary stream.
Parameters
[in] stream Stream from which the sparse matrix will be read.
[in] type Type of sparse matrix to allocate (CSR, CSC, TRIPLET)
Returns
The allocated sparse matrix.
Definition at line 1128 of file gsl_extension.cpp.
Referenced by transferOperator::scanTransition().
gsl_spmatrix_div_cols()
int gsl_spmatrix_div_cols (gsl_spmatrix * m, const gsl_vector * v, const double tol)
Divide each column of a compressed matrix by the corresponding vector element.
Parameters
[in] m compressed matrix to divide.
[in] v vector to divide the columns of the sparse matrix.
[in] tol threshold under which to avoid division by zero.
Returns
Exit status.
Definition at line 1071 of file gsl_extension.cpp.
References p.
Referenced by filterStochasticMatrix().
gsl_spmatrix_div_rows()
int gsl_spmatrix_div_rows (gsl_spmatrix * m, const gsl_vector * v, const double tol)
Divide each row of a compressed matrix by the corresponding vector element.
Parameters
[in] m compressed matrix to divide.
[in] v vector to divide the rows of the sparse matrix.
[in] tol threshold under which to avoid division by zero.
Returns
Exit status.
Definition at line 1014 of file gsl_extension.cpp.
References p.
Referenced by transferOperator::buildFromTransitionCount(), and filterStochasticMatrix().
gsl_spmatrix_get_colsum()
int gsl_spmatrix_get_colsum (gsl_vector * sum, const gsl_spmatrix * m)
Get the sum of the elements of a compressed matrix over each column.
Parameters
[out] sum Resulting vector of the sum of the columns.
[in] m Compressed matrix over which to sum.
Returns
Exit status.
Definition at line 948 of file gsl_extension.cpp.
References p.
Referenced by filterStochasticMatrix().
gsl_spmatrix_get_rowsum()
int gsl_spmatrix_get_rowsum (gsl_vector * sum, const gsl_spmatrix * m)
Get the sum of the elements of a compressed matrix over each row.
Parameters
[out] sum Resulting vector of the sum of the rows.
[in] m Compressed matrix over which to sum.
Returns
Exit status.
Definition at line 902 of file gsl_extension.cpp.
References p.
Referenced by filterStochasticMatrix().
gsl_spmatrix_get_sum()
double gsl_spmatrix_get_sum (const gsl_spmatrix * m)
Get the sum of the elements of a sparse matrix.
Parameters
[in] m Sparse matrix over which to sum.
Returns
Sum over all the elements of the sparse matrix.
Definition at line 993 of file gsl_extension.cpp.
Referenced by filterStochasticMatrix().
gsl_vector_complex_abs()
gsl_vector* gsl_vector_complex_abs (const gsl_vector_complex * v)
Get absolute values of complex vector.
Parameters
[in] v Complex vector for which to calculate the absolute value.
Returns
Real vector of absolute values.
Definition at line 352 of file gsl_extension.cpp.
Referenced by transferSpectrum::sort().
gsl_vector_complex_get_inner_product()
gsl_complex gsl_vector_complex_get_inner_product (const gsl_vector_complex * v, const gsl_vector_complex * w, const gsl_vector * mu)
Calculate inner product between two complex vectors for a given measure. The inner product of between and is equal to .
Parameters
[in] v Left vector (bra).
[in] w Right vector (ket).
[in] mu Measure with respect to which to calculate the inner product.
Returns
Inner product between the two vectors.
Get product i
Add product i
Definition at line 501 of file gsl_extension.cpp.
Referenced by transferSpectrum::getConditionNumbers(), transferSpectrum::getWeights(), gsl_vector_complex_get_norm(), transferSpectrum::makeBiorthonormal(), and normalizeFloquet().
gsl_vector_complex_get_norm()
double gsl_vector_complex_get_norm (const gsl_vector_complex * v, const gsl_vector * mu)
Calculate the norm of a complex vector for a given measure .
Parameters
[in] v Vector from which to calculate the norm.
[in] mu Measure with respect to which to calculate the norm.
Returns
Norm of the vector.
Copy vector
Get norm
Free
Definition at line 542 of file gsl_extension.cpp.
References gsl_vector_complex_get_inner_product().
Referenced by transferSpectrum::getConditionNumbers(), and normalizeFloquet().
gsl_vector_complex_log()
void gsl_vector_complex_log (gsl_vector_complex * res, const gsl_vector_complex * v)
Get complex logarithm of complex vector.
Parameters
[out] res Complex vector in which to save the logaritm.
[in] v Complex vector from which to calculate the logarithm.
Definition at line 298 of file gsl_extension.cpp.
Referenced by getFloquet().
gsl_vector_complex_max()
gsl_complex gsl_vector_complex_max (const gsl_vector_complex * v)
Find the maximum in absolute value of a complex vector.
Parameters
[in] v Complex vector from which to find the maximum. return Maximum in absolute value of a complex vector.
Find maximum
Definition at line 371 of file gsl_extension.cpp.
gsl_vector_complex_max_index()
size_t gsl_vector_complex_max_index (const gsl_vector_complex * v)
Find the index of the maximum in absolute value of a complex vector.
Parameters
[in] v Complex vector from which to find the index of maximum. return Index of the maximum in absolute value of the complex vector.
Find maximum
Definition at line 401 of file gsl_extension.cpp.
gsl_vector_complex_memcpy_imag()
int gsl_vector_complex_memcpy_imag (gsl_vector_complex * dst, const gsl_vector * src)
Copy vector to imaginary part of complex vector.
Parameters
[out] dst Destination complex vector to which copy imaginary part.
[in] src Source vector to copy.
Copy source vector to imaginary part of complex destination vector
Definition at line 332 of file gsl_extension.cpp.
gsl_vector_complex_memcpy_real()
int gsl_vector_complex_memcpy_real (gsl_vector_complex * dst, const gsl_vector * src)
Copy vector to real part of complex vector.
Parameters
[out] dst Destination complex vector to which copy real part.
[in] src Source vector to copy.
Copy source vector to real part of complex destination vector
Definition at line 311 of file gsl_extension.cpp.
Referenced by transferSpectrum::getWeights().
gsl_vector_complex_min()
gsl_complex gsl_vector_complex_min (const gsl_vector_complex * v)
Find the minimum in absolute value of a complex vector.
Parameters
[in] v Complex vector from which to find the minimum. return Minimum in absolute value of a complex vector.
Find minimum
Definition at line 434 of file gsl_extension.cpp.
gsl_vector_complex_min_index()
size_t gsl_vector_complex_min_index (const gsl_vector_complex * v)
Find the index of the minimum in absolute value of a complex vector.
Parameters
[in] v Complex vector from which to find the index of minimum. return Index of the minimum in absolute value of the complex vector.
Find minimum
Definition at line 464 of file gsl_extension.cpp.
Referenced by normalizeFloquet(), transferSpectrum::sort(), and sortSpectrum().
gsl_vector_complex_scale_real()
void gsl_vector_complex_scale_real (gsl_vector_complex * v, const double a)
Scale a complex vector with a real number.
Parameters
[in,out] v Vector to scale.
[in] a Real number with which to scale.
Definition at line 283 of file gsl_extension.cpp.
Referenced by getFloquet(), and normalizeFloquet().
gsl_vector_get_inner_product()
double gsl_vector_get_inner_product (const gsl_vector * v, const gsl_vector * w, const gsl_vector * mu)
Get the inner product of two vectors for a given measure. The inner product of between and is equal to .
Parameters
[in] v Left vector (bra).
[in] w Right vector (ket).
[in] mu Vector of the measure associated with the inner product.
Returns
Inner product.
Definition at line 71 of file gsl_extension.cpp.
References gsl_vector_get_sum().
Referenced by getPhaseDiffusion(), and gsl_vector_get_norm().
gsl_vector_get_mean()
double gsl_vector_get_mean (const gsl_vector * v)
Get the mean of the elements of a vector
Parameters
[in] v Vector over which to calculate the mean.
Returns
Mean of the vector.
Definition at line 173 of file gsl_extension.cpp.
References gsl_vector_get_sum().
Referenced by gsl_vector_get_var().
gsl_vector_get_norm()
double gsl_vector_get_norm (const gsl_vector * v, const gsl_vector * mu)
Get the norm of a vector for a given measure . The norm of is equal to .
Parameters
[in] v Vector of which to calculate the norm.
[in] mu Vector of the measure associated with the norm.
Returns
Norm of the vector.
Definition at line 110 of file gsl_extension.cpp.
References gsl_vector_get_inner_product().
Referenced by fixedPointCont::correct(), periodicOrbitCont::correct(), fixedPointCorr::findSolution(), periodicOrbitCorr::findSolution(), and normalizeFloquet().
gsl_vector_get_prod()
double gsl_vector_get_prod (const gsl_vector * v)
Get product of vector elements.
Parameters
[in] v Vector from which to multiply the elements.
Returns
Product of vector elements.
Definition at line 139 of file gsl_extension.cpp.
gsl_vector_get_std()
double gsl_vector_get_std (const gsl_vector * v)
Get the standard deviation of the elements of a vector
Parameters
[in] v Vector over which to calculate the standard deviation.
Returns
Standard Deviation of the vector.
Definition at line 214 of file gsl_extension.cpp.
References gsl_vector_get_var().
gsl_vector_get_sum()
double gsl_vector_get_sum (const gsl_vector * v)
Get sum of vector elements.
Parameters
[in] v Vector from which to sum the elements.
Returns
Sum of vector elements.
Definition at line 50 of file gsl_extension.cpp.
Referenced by gsl_matrix_get_colsum(), gsl_matrix_get_rowsum(), gsl_vector_get_inner_product(), gsl_vector_get_mean(), and gsl_vector_normalize().
gsl_vector_get_var()
double gsl_vector_get_var (const gsl_vector * v)
Get the variance of the elements of a vector
Parameters
[in] v Vector over which to calculate the variance.
Returns
Variance of the vector.
Definition at line 185 of file gsl_extension.cpp.
References gsl_vector_get_mean().
Referenced by gsl_vector_get_std().
gsl_vector_normalize()
int gsl_vector_normalize (gsl_vector * v)
Normalize vector by the sum of its elements.
Parameters
[in] v Vector to normalize.
Definition at line 33 of file gsl_extension.cpp.
References gsl_vector_get_sum().
Referenced by transferOperator::buildFromTransitionCount(), and filterStochasticMatrix().
gsl_vector_sqrt()
int gsl_vector_sqrt (gsl_vector * v)
Get the square root of the elements of a vector.
Parameters
[in,out] v Vector for which to calculate the square root.
Returns
Exit status.
Definition at line 18 of file gsl_extension.cpp.
Referenced by gsl_matrix_get_std().
gsl_vector_uint_get_prod()
double gsl_vector_uint_get_prod (const gsl_vector_uint * v)
Get product of vector elements.
Parameters
[in] v Vector from which to multiply the elements.
Returns
Product of vector elements.
Definition at line 156 of file gsl_extension.cpp.