ergoPack: example/simulation/simSDDE.cpp File Reference
simSDDE.cpp File Reference
Simulate a Stochastic Delay Differential Equation.
#include <cstdlib>
#include <cstdio>
#include <iostream>
#include <cmath>
#include <cstring>
#include <gsl/gsl_sf_log.h>
#include <gsl/gsl_vector.h>
#include <gsl/gsl_matrix.h>
#include <gsl/gsl_rng.h>
#include <gsl/gsl_randist.h>
#include <libconfig.h++>
#include <ODESolvers.hpp>
#include <SDESolvers.hpp>
#include <SDDESolvers.hpp>
Functions
void readConfig (const char *cfgFileName)
User defined function to get parameters from a cfg file using libconfig.
int main (int argc, char *argv[])
Simulation of an Stochastic Delay Differential Equation.
Variables
char caseName [256]
Name of the case to simulate.
char fileFormat [256]
File format of output ("txt" or "bin")
char resDir [256]
Root directory in which results are written.
int dim
Dimension of the phase space.
size_t nDelays
Number of delays.
std::vector< gsl_vector * > * driftPolynomials
gsl_vector * delaysDays
Delays in days.
gsl_vector_uint * delays
Delays in number of time steps.
char delayName [256]
Name associated with the delays.
gsl_matrix * Q
Diffusion matrix.
gsl_vector * initStateCst
State to define constant initial state history.
double LCut
Length of the time series without spinup.
double spinup
Length of initial spinup period to remove.
double L
Total length of integration.
double dt
Time step of integration.
double printStep
Time step of output.
size_t printStepNum
Time step of output in number of time steps of integration.
char dstFileName [256]
Destination file name.
Detailed Description
Simulate a Stochastic Delay Differential Equation with polynomial vector fields.
Definition in file simSDDE.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Simulation of an Stochastic Delay Differential Equation. After parsing the configuration file, a delayed polynomial vector field for the drift, a diffusion matrix and an Euler-Maruyama stochastic numerical scheme are defined. The model is then integrated forward and the results saved.
Definition at line 60 of file simSDDE.cpp.
References delays, delaysDays, dim, driftPolynomials, dstFileName, dt, fileFormat, initStateCst, modelSDDE::integrateForward(), L, nDelays, printStepNum, Q, readConfig(), and spinup.
readConfig()
void readConfig (const char * cfgFileName)
Sparse all configuration sections.
Sparse configuration file using libconfig++ to define all parameters of the case.
Get paths
Get model settings
Get simulation settings
Definition at line 147 of file simSDDE.cpp.
References A, caseName, delayName, delays, delaysDays, dim, driftPolynomials, dstFileName, dt, fileFormat, initState, initStateCst, L, LCut, nDelays, printStep, printStepNum, Q, resDir, and spinup.
Referenced by main().
Variable Documentation
delayName
char delayName[256]
Name associated with the number and values of the delays.
Definition at line 40 of file simSDDE.cpp.
Referenced by readConfig().
driftPolynomials
std::vector<gsl_vector *>* driftPolynomials
Vector of polynomials to define the vector fields for each delay
Definition at line 37 of file simSDDE.cpp.
Referenced by main(), and readConfig().