ergoPack: simulation/simOU.cpp File Reference
simOU.cpp File Reference
Examples
Simulate a multi-dimensional Ornstein-Uhlenbeck process.
#include <cstdlib>
#include <cstdio>
#include <iostream>
#include <cmath>
#include <cstring>
#include <gsl/gsl_sf_log.h>
#include <gsl/gsl_vector.h>
#include <gsl/gsl_matrix.h>
#include <gsl/gsl_rng.h>
#include <gsl/gsl_randist.h>
#include <libconfig.h++>
#include <SDESolvers.hpp>
#include <ODESolvers.hpp>
Functions
void readConfig (const char *cfgFileName)
User defined function to get parameters from a cfg file using libconfig.
int main (int argc, char *argv[])
Simulation of an Ornstein-Uhlenbeck process.
Variables
char caseName [256]
Name of the case to simulate.
char file_format [256]
File format of output ("txt" or "bin")
char resDir [256]
Root directory in which results are written.
int dim
Dimension of the phase space.
gsl_matrix * A
Matrix of the linear drift.
gsl_matrix * Q
Diffusion matrix.
gsl_vector * initState
Initial state.
double LCut
Length of the time series without spinup.
double spinup
Length of initial spinup period to remove.
double L
Total length of integration.
double dt
Time step of integration.
double printStep
Time step of output.
size_t printStepNum
Time step of output in number of time steps of integration.
char postfix [256]
Postfix of destination files.
char dstFileName [256]
Destination file name.
Detailed Description
Simulate a multi-dimensional Ornstein-Uhlenbeck process.
Definition in file simOU.cpp.
Function Documentation
int main (int argc, char * argv[])
Simulation of an Ornstein-Uhlenbeck process. After parsing the configuration file, a linear vector field for the drift, a diffusion matrix and an Euler-Maruyama stochastic numerical scheme are defined. The model is then integrated forward and the results saved.
Definition at line 59 of file simOU.cpp.
References A, dim, dstFileName, dt, file_format, initState, modelStochastic::integrateForward(), L, printStepNum, Q, readConfig(), and spinup.
void readConfig (const char * cfgFileName)
Sparse configuration file using libconfig++ to define all parameters of the case.
Get paths
Get model settings
Get simulation settings
Definition at line 134 of file simOU.cpp.
Referenced by main().
Variable Documentation
gsl_vector* initState
Initial state for simulation.
Definition at line 40 of file simOU.cpp.
Referenced by main(), and readConfig().