ergoPack: spectrum/spectrum.cpp File Reference
spectrum.cpp File Reference
Examples
Get spectrum of transfer operators.
#include <cstdlib>
#include <cstdio>
#include <cstring>
#include <stdexcept>
#include <iostream>
#include <gsl/gsl_vector.h>
#include <gsl/gsl_matrix.h>
#include <gsl/gsl_math.h>
#include <transferOperator.hpp>
#include <transferSpectrum.hpp>
#include "../cfg/readConfig.hpp"
Functions
int main (int argc, char *argv[])
Calculate the spectrum of a transfer operator.
Detailed Description
Get spectrum of transfer operators.
Definition in file spectrum.cpp.
Function Documentation
int main (int argc, char * argv[])
After parsing the configuration file, the transition matrices are then read from matrix files in coordinate format. The Eigen problem is then defined and solved using ARPACK++. Finally, the results are written to file.
Definition at line 29 of file spectrum.cpp.
References config, configFileName, transferSpectrum::EigProbBackward, transferSpectrum::EigProbForward, transferOperator::finalDist, freeConfig(), getBackwardEigenvectors, getForwardEigenvectors, transferSpectrum::getSpectrumBackward(), transferSpectrum::getSpectrumForward(), gridPostfix, transferOperator::initDist, makeBiorthonormal, transferSpectrum::makeBiorthonormal(), N, nev, nLags, postfix, readConfig(), resDir, transferOperator::scanBackwardTransition(), transferOperator::scanFinalDist(), transferOperator::scanForwardTransition(), transferOperator::scanInitDist(), transferOperator::setFinalDist(), transferOperator::setInitDist(), stationary, tauRng, transferSpectrum::writeSpectrumBackward(), and transferSpectrum::writeSpectrumForward().