ergoPack: include/transferOperator.hpp File Reference
transferOperator.hpp File Reference
Calculate discretized approximation of transfer/Koopman operators from time series.
#include <iostream>
#include <vector>
#include <stdexcept>
#include <ios>
#include <gsl/gsl_math.h>
#include <gsl/gsl_vector.h>
#include <gsl/gsl_matrix.h>
#include <gsl/gsl_spmatrix.h>
#include <ergoPack/gsl_extension.h>
#include <ergoPack/ergoGrid.hpp>
Classes
class transferOperator
Transfer operator class.
Functions
gsl_spmatrix * getTransitionCountTriplet (const gsl_matrix_uint *gridMem, size_t N)
Get triplet vector from membership matrix.
int filterStochasticMatrix (gsl_spmatrix *M, gsl_vector *rowCut, gsl_vector *colCut, double tol, int norm)
Remove weak nodes from a transition matrix.
Detailed Description
Calculate Galerkin approximation of transfer/Koopman operators from time series. The result is given as forward and backward Markov transition matrices approximating the transfer and Koopman operator, respectively, as well as the initial and final distrtutions associated to them.
Coordinate format with a one line header is followed for printing and scanning of the sparse transition matrices. The first line is a header giving the number of rows, columns and non-zero elements: M N nnz Each following line gives the coordinate of one matrix element as its row, column and value: i j d
Definition in file transferOperator.hpp.
Function Documentation
int filterStochasticMatrix (gsl_spmatrix * M, gsl_vector * rowCut, gsl_vector * colCut, double tol, int norm)
Set weak states to 0 from a stochastic matrix and its distributions based on initial and final probability of each Markov state. Attention: elements are not actually removed from sparse matrix.
Parameters
[in,out] M Compressed transition matrix to filter.
[in] rowCut The probability distribution associated with each row.
[in] colCut The probability distribution associated with each column.
[in] tol Probability under which Markov states are removed.
[in] norm Choice of normalization,
norm = 0: normalize over all elements,
norm = 1: to right stochastic,
norm = 2: to left stochastic,
no normalization for any other choice.
Check which nodes should be filtered and set distribution to 0
Make matrix and vectors stochastic again
Free
Definition at line 667 of file transferOperator.hpp.
References gsl_vector_normalize().
Referenced by transferOperator::filter(), and transferOperator::getN().
gsl_spmatrix * getTransitionCountTriplet (const gsl_matrix_uint * gridMem, size_t N)
Get the triplet vector counting the transitions from pairs of grid boxes from the grid membership matrix.
Parameters
[in] gridMem Grid membership matrix.
[in] N Size of the grid.
Returns
Triplet vector counting the transitions.
Allocate triplet sparse matrix
Record transitions
Add transition triplet, summing if duplicate
Definition at line 621 of file transferOperator.hpp.
Referenced by transferOperator::getN(), and transferOperator::~transferOperator().