ergoPack: include/transferSpectrum.hpp File Reference
transferSpectrum.hpp File Reference
Get spectrum of transferOperator using ARPACK++.
#include <cstdlib>
#include <cstdio>
#include <vector>
#include <stdexcept>
#include <gsl/gsl_complex.h>
#include <gsl/gsl_complex_math.h>
#include <gsl/gsl_vector.h>
#include <gsl/gsl_matrix.h>
#include <gsl/gsl_spmatrix.h>
#include <gsl/gsl_permutation.h>
#include <gsl/gsl_permute_vector.h>
#include <gsl/gsl_sort_vector.h>
#include <arpack++/arsnsym.h>
#include <ergoPack/transferOperator.hpp>
Classes
struct configAR
Utility structure used to give configuration options to ARPACK++.
class gsl_spmatrix2AR
Interface from GSL sparse matrices to ARPACK++.
class transferSpectrum
Transfer operator spectrum.
Functions
void getSpectrumAR (const int nev, ARNonSymStdEig< double, gsl_spmatrix2AR > *EigProb, gsl_spmatrix2AR *gsl2AR, configAR cfgAR, gsl_vector_complex *EigVal, gsl_matrix_complex *EigVec)
Get spectrum of a nonsymmetric matrix using ARPACK++.
void writeSpectrumAR (FILE *fEigVal, FILE *fEigVec, const gsl_vector_complex *EigVal, const gsl_matrix_complex *EigVec)
Write spectrum of a nonsymmetric matrix using ARPACK++.
Variables
configAR defaultCfgAR = {"LM", 0, 0., 0, NULL, true}
Detailed Description
Analyse the spectrum of the forward and backward transition matrices of a transferOperator object using ARPACK++.
Definition in file transferSpectrum.hpp.
Function Documentation
void getSpectrumAR (const int nev, ARNonSymStdEig< double, gsl_spmatrix2AR > * EigProb, gsl_spmatrix2AR * gsl2AR, configAR cfgAR, gsl_vector_complex * EigVal, gsl_matrix_complex * EigVec)
Get spectrum of a nonsymmetric matrix using ARPACK++.
Parameters
[in] nev Number of eigenvalues and eigenvectors to find.
[in,out] EigProb Eigen problem to use.
[in] gsl2AR Object interfacing the GSL sparse matrix to ARPACK++.
[in] cfgAR Configuration options passed as a configAR object.
[out] EigVal Found eigenvalues.
[out] EigVec Found eigenvectors.
Define non-hermitian eigenvalue problem
Find eigenvalues and left eigenvectors with ARPACK++
Save eigenvalues and eigenvectors and their complex conjugate
Definition at line 710 of file transferSpectrum.hpp.
References configAR::AutoShift, gsl_spmatrix2AR::M, configAR::maxit, gsl_spmatrix2AR::MultMv(), configAR::ncv, configAR::resid, configAR::tol, and configAR::which.
Referenced by transferSpectrum::getSpectrumBackward(), transferSpectrum::getSpectrumForward(), and transferSpectrum::setConfig().
void writeSpectrumAR (FILE * fEigVal, FILE * fEigVec, const gsl_vector_complex * EigVal, const gsl_matrix_complex * EigVec)
Write complex eigenvalues and eigenvectors obtained as arrays from ARPACK++.
Parameters
[in] fEigVal File descriptor for eigenvalues.
[in] fEigVec File descriptor for eigenvectors.
[in] EigVal Array of eigenvalues real parts.
[in] EigVec Array of eigenvectors.
Check for printing errors
Check for printing errors
Definition at line 788 of file transferSpectrum.hpp.
Referenced by transferSpectrum::setConfig(), transferSpectrum::writeSpectrumBackward(), and transferSpectrum::writeSpectrumForward().
Variable Documentation
configAR defaultCfgAR = {"LM", 0, 0., 0, NULL, true}
Declare default structure looking for largest magnitude eigenvalues
Definition at line 47 of file transferSpectrum.hpp.
Referenced by readConfig().