ergoPack: transfer/transfer.cpp File Reference
transfer.cpp File Reference
Examples
Get transition matrices and distributions directly from time series.
#include <cstdlib>
#include <cstdio>
#include <cstring>
#include <stdexcept>
#include <gsl/gsl_vector.h>
#include <gsl/gsl_matrix.h>
#include <gsl/gsl_math.h>
#include <gsl/gsl_sf_log.h>
#include <transferOperator.hpp>
#include <gsl_extension.h>
#include "../cfg/readConfig.hpp"
Functions
int main (int argc, char *argv[])
Calculate transfer operators from time series.
Variables
char resDir [256]
Root directory in which results are written.
char caseName [256]
Name of the case to simulate.
char file_format [256]
File format of output ("txt" or "bin")
char delayName [256]
Name associated with the number and values of the delays.
int dim
Dimension of the phase space.
double LCut
Length of the time series without spinup.
double spinup
Length of initial spinup period to remove.
double L
Total length of integration.
double dt
Time step of integration.
double printStep
Time step of output.
size_t printStepNum
Time step of output in number of time steps of integration.
char srcPostfix [256]
Postfix of simulation file.
char srcFileName [256]
Name of the source simulation file.
char dstFileName [256]
Destination file name.
size_t nt0
Number of time steps of the source time series.
size_t nt
Number of time steps of the observable.
int dimObs
Dimension of the observable.
size_t embedMax
Maximum lag for the embedding.
gsl_vector_uint * components
Components in the time series used by the observable.
gsl_vector_uint * embedding
Embedding lags for each component.
bool readGridMem
Whether to read the grid membership vector.
size_t N
Dimension of the grid.
gsl_vector_uint * nx
Number of grid boxes per dimension.
gsl_vector * nSTDLow
Number of standard deviations below mean to span by the grid.
gsl_vector * nSTDHigh
Number of standard deviations above mean to span by the grid.
size_t nLags
Number of transition lags for which to calculate the spectrum.
gsl_vector * tauRng
Lags for which to calculate the spectrum.
int nev
Number of eigenvectors to calculate.
char obsName [256]
Name associated with the observable.
char gridPostfix [256]
Postfix associated with the grid.
char gridFileName [256]
File name for the grid file.
configAR config
Configuration data for the eigen problem.
char configFileName [256]
Name of the configuration file.
bool stationary
Whether the problem is stationary or not.
bool getForwardEigenvectors
Whether to get forward eigenvectors.
bool getBackwardEigenvectors
Whether to get backward eigenvectors.
bool makeBiorthonormal
Whether to make eigenvectors biorthonormal.
Detailed Description
Get transition matrices and distributions from a long time series (e.g. simulation output). Takes as first a configuration file to be parsed with libconfig C++ library. First read the observable and get its mean and standard deviation used to adapt the grid. A rectangular grid is used here. A grid membership vector is calculated for each time series assigning to each realization a grid box. Then, the membership matrix is calculated for a given lag. The forward transition matrices as well as the initial distributions are calculated from the membership matrix. Note that, since the transitions are calculated from long time series, the problem must be autonomous and ergodic (stationary) so that the backward transition matrix and final distribution need not be calculated. Finally, the results are printed.
Definition in file transfer.cpp.
Function Documentation
int main (int argc, char * argv[])
After parsing the configuration file, the time series is read and an observable is designed selecting components with a given embedding lag. A membership vector is then built from the observable, attaching the box they belong to to every realization. The membership vector is then converted to a membership matrix for different lags and the transfer operators built. The results are then written to file.
Definition at line 87 of file transfer.cpp.
References components, configFileName, dim, dimObs, embedding, embedMax, getGridMemVector(), gridFileName, gridPostfix, memVector2memMatrix(), N, nLags, nSTDHigh, nSTDLow, nt, nt0, nx, postfix, transferOperator::printBackwardTransition(), transferOperator::printFinalDist(), transferOperator::printForwardTransition(), Grid::printGrid(), transferOperator::printInitDist(), printStep, readConfig(), readGridMem, resDir, srcFileName, stationary, and tauRng.